### ISSUE TITLE
Flatpack on ARM RPI 3B+ Equalizer bug

### ISSUE THREAD

**Issue by clumster** [wwmm/pulseeffects#464] opened 2019-03-18 04:56 UTC
After installing flatpack version on RPI 3B+ audio does work through most of the other plugins but not the Equalizer. Sound stops and then resumes once the "on" button is toggled. I can provide more system information if the bug is unable to be replicated.

**Comment by wwmm** [comment] 2019-03-18 14:01
It would be good to know if a native package is working in the RPI. We use the equalizer https://lsp-plug.in/?page=manuals&section=para_equalizer_x32_lr from [lsp-plugins](https://github.com/sadko4u/lsp-plugins) and I know that in other to have more performance it uses some vector instructions that are platform dependent. But I think ARM is supported. Try to run PE in debug mode `G_MESSAGES_DEBUG=pulseeffects flatpak run com.github.wwmm.pulseeffects`. Maybe what is printed in the terminal will help.

@AsavarTzeth did you have any trouble compiling for ARM architecture?

**Comment by wwmm** [comment] 2019-03-18 14:10
I just saw on lsp-plugins README `ARMv7-AR (experimental, tested on Raspberry Pi 3 Model B)`. Maybe it is not supported on B+. It may be worth to open an issue in https://github.com/sadko4u/lsp-plugins to confirm that.

**Comment by AsavarTzeth** [comment] 2019-03-18 15:39
I had lots of troubles! But I did manage to build it.

The lsp-plugins build system is a mess of abused Makefiles, with tons of platform assumptions. Someone should request they redo it. Preferably using meson :)

This one might have a simpler answer though. There is no 64-bit arm support in lsp-plugins, so I had to skip that module for aarch64. The Rpi3+ SoC is 64-bit according to the [pi documentation](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2837b0/README.md). Although apparently the official raspbian image is 32-bit? What os and arch are you using?

I am pretty sure upstream just builds and distribute 32-bit arm binaries.

In case I somehow made a build error, you can find the relevant commit here: https://github.com/flathub/com.github.wwmm.pulseeffects/commit/d23273f51b93e4be1d1e4599b174d2e2cb8df240

**Comment by AsavarTzeth** [comment] 2019-03-18 15:42
Does RPI or arm in general have backwards compatibility, similar to x86? If so you might try explicitly installing the 32-bit version:

```
flatpak install flathub com.github.wwmm.pulseeffects//arm
```

**Comment by clumster** [comment] 2019-03-19 02:57
System : Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

That's the system. I am currently reinstalling Raspbian because the system broke due to another issue. I will try the suggests that you all have made and see how I get on. I do find it peculiar that all of the other plugins seem to work perfectly and only the EQ seems to freeze up.

**Comment by wwmm** [comment] 2019-03-19 03:31
That is probably because the equalizer is using vector instructions and the other plugins don't.

**Comment by AsavarTzeth** [comment] 2019-03-19 07:30
By the way I fixed a typo in the install command. However since `armv7l` is 32-bit it should be the same you are using already.

**Comment by sadko4u** [comment] 2019-03-19 07:30
> The lsp-plugins build system is a mess of abused Makefiles, with tons of platform assumptions. Someone should request they redo it. Preferably using meson :)

The meson build system is too poor to compile LSP code.
To utilize SIMD instructions and make the rest code portable between other CPUs without recompiling it, we need to compile some files with special flags. Meson does not allow this *by design*:
https://github.com/mesonbuild/meson/issues/1367

**Comment by AsavarTzeth** [comment] 2019-03-19 07:41
> The meson build system is too poor to compile LSP code.
To utilize SIMD instructions and make the rest code portable between other CPUs without recompiling it, we need to compile some files with special flags. Meson does not allow this by design:
mesonbuild/meson#1367

Well that's enlightening. I would obviously want to hear from a meson expert, if there is a better way to do it, but I respect that you looked into it.

I mean even autotools would be better than the current solution. But I could not suggest that with good confidence, given how complex it can become.

**Comment by sadko4u** [comment] 2019-03-19 07:53
> How about CMake?

I hadn't much time to look into it. But according to my previous research, CMake had some troubles with dependencies on files generated at compile-time. But seems it is already not a problem:
https://crascit.com/2017/04/18/generated-sources-in-cmake-builds/

**Comment by sadko4u** [comment] 2019-03-19 11:07
FYI, I've just merged AArch64 experimental support into **devel** branch:
https://github.com/sadko4u/lsp-plugins/commit/444a72429ab46347e5fd49ce74f55a7cbe27142a

According to performance test related to digital filters, I get disappointing statistics.

Performance test on armv7a architecture, Raspbian:
```
┌Case──────────────────────────┬Time[s]┬───Iter┬Samp[s]┬────Est┬Perf[i/s]┬Cost[us/i]┬Rel[%]┐
│native::biquad_process_x1 x8  │  30.69│ 320000│  30.00│ 312799│ 10426.64│   95.9081│100.00│
│neon_d32::biquad_process_x1 x8│  30.14│ 440000│  30.00│ 437906│ 14596.88│   68.5078│140.00│
├──────────────────────────────┼───────┼───────┼───────┼───────┼─────────┼──────────┼──────┤
│native::biquad_process_x2 x4  │  30.25│ 380000│  30.00│ 376850│ 12561.67│   79.6073│100.00│
│neon_d32::biquad_process_x2 x4│  30.06│ 650000│  30.00│ 648660│ 21622.02│   46.2491│172.13│
├──────────────────────────────┼───────┼───────┼───────┼───────┼─────────┼──────────┼──────┤
│native::biquad_process_x4 x2  │  30.26│ 490000│  30.00│ 485772│ 16192.42│   61.7573│100.00│
│neon_d32::biquad_process_x4 x2│  30.05│1450000│  30.00│1447379│ 48245.99│   20.7271│297.95│
├──────────────────────────────┼───────┼───────┼───────┼───────┼─────────┼──────────┼──────┤
│native::biquad_process_x8 x1  │  30.06│ 480000│  30.00│ 478975│ 15965.84│   62.6337│100.00│
│neon_d32::biquad_process_x8 x1│  30.08│1420000│  30.00│1416234│ 47207.82│   21.1829│295.68│
└──────────────────────────────┴───────┴───────┴───────┴───────┴─────────┴──────────┴──────┘
```

Performance test on aarch64 architecture, Arch Linux:
```
┌Case────────────────────────┬Time[s]┬──Iter┬Samp[s]┬───Est┬Perf[i/s]┬Cost[us/i]┬Rel[%]┐
│native::biquad_process_x1 x8│  30.78│180000│  30.00│175465│  5848.84│  170.9742│100.00│
├────────────────────────────┼───────┼──────┼───────┼──────┼─────────┼──────────┼──────┤
│native::biquad_process_x2 x4│  31.12│260000│  30.00│250668│  8355.63│  119.6797│100.00│
├────────────────────────────┼───────┼──────┼───────┼──────┼─────────┼──────────┼──────┤
│native::biquad_process_x4 x2│  30.25│280000│  30.00│277649│  9254.98│  108.0500│100.00│
├────────────────────────────┼───────┼──────┼───────┼──────┼─────────┼──────────┼──────┤
│native::biquad_process_x8 x1│  30.89│280000│  30.00│271935│  9064.51│  110.3203│100.00│
└────────────────────────────┴───────┴──────┴───────┴──────┴─────────┴──────────┴──────┘
```

As you see, using SIMD NEON CPU instruction set for 32-bit ARM architecture allows to process ~47207 buffers of 512 samples per second with 8 sequential biquad filters versus 15965 buffers for native implementation.
For AArch64 architecture, the situation is even worse: only 9064 buffers of 512 samples per second can be processed with 8 sequential biquad filters. It can be a side effect of a poor power supply but I can try to switch power supplies only within few days.

**Comment by clumster** [comment] 2019-03-19 12:03
Here is some more terminal output from what happens when the equalizer is turned on. Not sure if it's of use but it may confirm what has already been said. 

`pi@raspberrypi:~` $ flatpak run com.github.wwmm.pulseeffects

(pulseeffects:3): dbind-WARNING **: 00:58:53.917: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(pulseeffects:3): GLib-GObject-WARNING **: 00:59:06.477: g_object_set_is_valid_property: object class 'GstPulseSrc' has no property named 'XQPr\u0010'
lilv_lib_open(): error: Failed to open library /app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so (/app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so: undefined symbol: _ZN3arm8dsp_initEv)
lilv_lib_open(): error: Failed to open library /app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so (/app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so: undefined symbol: _ZN3arm8dsp_initEv)
lilv_lib_open(): error: Failed to open library /app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so (/app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so: undefined symbol: _ZN3arm8dsp_initEv)

(pulseeffects:3): pulseeffects-CRITICAL **: 00:59:45.877: sie: Internal data stream error.
lilv_lib_open(): error: Failed to open library /app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so (/app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so: undefined symbol: _ZN3arm8dsp_initEv)
lilv_lib_open(): error: Failed to open library /app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so (/app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so: undefined symbol: _ZN3arm8dsp_initEv)
lilv_lib_open(): error: Failed to open library /app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so (/app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so: undefined symbol: _ZN3arm8dsp_initEv)

(pulseeffects:3): pulseeffects-CRITICAL **: 00:59:46.334: sie: Internal data stream error.
lilv_lib_open(): error: Failed to open library /app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so (/app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so: undefined symbol: _ZN3arm8dsp_initEv)
lilv_lib_open(): error: Failed to open library /app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so (/app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so: undefined symbol: _ZN3arm8dsp_initEv)
lilv_lib_open(): error: Failed to open library /app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so (/app/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so: undefined symbol: `_ZN3arm8dsp_initEv)`

**Comment by sadko4u** [comment] 2019-03-19 12:11
It seems to be a bad build. The *.so file tires to call **arm::dsp_init** function that normally should be present. But due to changed of compilation process the implementation of **arm::dsp_init** function was not linked to the final binary.

**Comment by clumster** [comment] 2019-03-19 12:15
@sadko4u Therefore it is a fixable bug and not an architecture limitation?

**Comment by sadko4u** [comment] 2019-03-19 12:15
Here's the implementation of **dsp::init**:
https://github.com/sadko4u/lsp-plugins/blob/663a4f1422527c07c3a1e1e01b408392348a1691/src/dsp/arm.cpp#L300

**Comment by sadko4u** [comment] 2019-03-19 12:18
> @sadko4u Therefore it is a fixable bug and not an architecture limitation?
Yes, it's fixable. I build my binaries under ARM hardware but Flatpak seems to perform a cross-build, that's why couple of hacks were injected into build process that broke the final build. You may try to replace binaries with official builds:
https://github.com/sadko4u/lsp-plugins/releases/tag/lsp-plugins-1.1.7

**Comment by AsavarTzeth** [comment] 2019-03-19 12:57
Correct. It is either cross-compilation or a virtual environment; likely something like qemu-user-static. Either way there is no possible way to build and distribute the plugins with SIMD NEON support on Flathub.

It is also not possible to replace the binaries. You would have to modify the `com.github.wwmm.pulseeffects.yml` manifest and build your own flatpak.

On that topic though. I could be convinced to ship binaries for arm instead (assuming it works fine). Would you be willing to test the end-result if I pushed that to a beta branch @clumster? Although not preferable, I don't think this is against Flathub policies.

**Comment by sadko4u** [comment] 2019-03-19 13:03
> Correct. It is either cross-compilation or a virtual environment; likely something like qemu-user-static. Either way there is currently no possible way to build and distribute lsp-plugins for arm, with SIMD NEON support, on Flathub.

And what's the problem of building the package 'as-is'? LSP plugins do dynamically detect NEON support and enable the corresponding NEON-optimized functions only if the machine provides the NEON instruction set.

**Comment by AsavarTzeth** [comment] 2019-03-19 13:22
Well if you want the error I got from the failing builds, the last time I tried:

```
{standard input}: Assembler messages:
{standard input}:15039: Error: garbage following instruction -- `orr r5,r5,LSL $1'
{standard input}:15207: Error: garbage following instruction -- `orr r8,r8,LSL $1'
{standard input}:15522: Error: garbage following instruction -- `orr r5,r5,LSL $1'
{standard input}:15688: Error: garbage following instruction -- `orr lr,lr,LSL $1'
  g++ decode.cpp
  g++ phase_detector.cpp
  g++ widgets/LSPButton.cpp
  g++ CtlSwitch.cpp
  g++ CtlValuePort.cpp
{standard input}:19681: Error: garbage following instruction -- `subs r5,r3,LSL $1'
{standard input}:20600: Error: garbage following instruction -- `subs r6,r3,LSL $1'
  g++ graph_equalizer.cpp
make[2]: *** [Makefile:77: /run/build/lsp-plugins/.build/src/dsp/neon-d32.o] Error 1
make[1]: *** [Makefile:57: dsp] Error 2
```

If you want a fresh tests with the latest release and a complete build log I could certainly provide it. In fact, I will do that immediately.

**Comment by sadko4u** [comment] 2019-03-19 13:27
> Well if you want the error I got from the failing builds, the last time I tried:

It would be nice to look at the complit compilation command. You can obtain it by issuing the following command:
```
make SHELL='bash -x'
```

**Comment by sadko4u** [comment] 2019-03-19 13:32
I've created related issue: https://github.com/sadko4u/lsp-plugins/issues/35
Please submit all logs there to not to pollute this topic.

**Comment by AsavarTzeth** [comment] 2019-03-19 13:33
Just noticed and was about to ask the same thing.

**Comment by sadko4u** [comment] 2019-03-21 08:22
Short status update: @AsavarTzeth reported that LSP plugins now properly build for Flatpak for both ARMv7-AR and AArch64 architectures, the 1.1.9 release of LSP Plugins with critical fixes is planned at the end of the current week.

**Comment by sadko4u** [comment] 2019-03-23 19:01
The 1.1.9 release is out! I believe it is already packaged with FlatPak.

**Comment by clumster** [comment] 2019-03-24 04:29
Thanks for the update and the attentiveness, are you able to confirm that the issue is resolved? I am unable to at the moment.

**Comment by AsavarTzeth** [comment] 2019-03-24 08:50
May I ask why? I am guessing its because I have not actually gotten a stable build out yet. There is a test build if you are interested:

```
flatpak install --user https://dl.flathub.org/build-repo/1569/com.github.wwmm.pulseeffects.flatpakref
```

If you prefer to wait, I just pushed a stable build job. It will likely be available within the hour.

**Comment by mikhailnov** [comment] 2019-03-24 10:01
@AsavarTzeth as for "Disable Advanced SIMD or NEON on arm", it was not required when building on Launchpad both for 32-bit armv7 and 64-bit armv8, adding `+= -Wa,-mimplicit-it=thumb` was also not required. I think Launchpad builds on real hardware, does Flathub build in qemu emulator?

**Comment by AsavarTzeth** [comment] 2019-03-24 10:13
> Correct. It is either cross-compilation or a virtual environment; likely something like qemu-user-static. Either way there is currently no possible way to build and distribute lsp-plugins for arm, with SIMD NEON support, on Flathub.

This is since several days irrelevant. Everything is fixed now and no patches are used.

**Comment by AsavarTzeth** [comment] 2019-03-24 10:35
@clumster There is now a new stable build which should fix your issue. It also includes the latest pulseeffects update. I have not tested it on actual ARM hardware myself, so it would be interesting to know it works.

**Comment by clumster** [comment] 2019-03-24 22:52
@AsavarTzeth Was just in the process of changing distros on my Pi. I can confirm that the equalizer works on the most recent release of Arch Linux (as of the date of this post) for the RPI 3B+ if installed using Flatpak, the AUR version will not work.

I am just moving back to Raspbian Stretch. Performance of the Pulse Effects Equalizer on Arch with XFCE is usable, although default latency does not have any glaring buffer issues, there is not much headroom for any other processes on the Pi.

**Closed** 2019-03-24 23:45 UTC

**Comment by clumster** [comment] 2019-03-25 11:44
I can confirm again that Pulse Effects Equalizer also now works without issue on RPI 3B+ running the most recent Raspbian Stretch release as of the date of this post.
