### ISSUE TITLE
Taskbar and switcher icons not showing up.

### ISSUE THREAD

**Issue by mthqwork** [wwmm/pulseeffects#331] opened 2018-08-30 13:19 UTC
This is a problem what I have for months now, but can't figure out what's wrong,
as the author also using Arch linux but didnt noticed the issue. 

![image](https://user-images.githubusercontent.com/19063751/44854037-d5994200-ac67-11e8-9fc4-7bc8f8eebf01.png)
![image](https://user-images.githubusercontent.com/19063751/44854065-e649b800-ac67-11e8-9fe0-aff27bf4d25a.png)

Here is a quick xprop from PE's window:
https://pastebin.com/DZTN9pzp

My DE is XFCE 4.12.

The icon shows up properly in launcher and in plank.
What could be wrong? 
Thanks

**Comment by wwmm** [comment] 2018-08-30 14:33
If you have this problem with the new and the old icon the only thing that comes to my mind is the fact that the icon is a svg file. Maybe this taskbar does not accepts svg

**Comment by mthqwork** [comment] 2018-08-31 09:43
I had problem with old, but have the problem with new also. 
Yes maybe, i have another apps with broken icons - they also offer svg only icon.

It's stock XFCE4 taskbar.

If I change the app icon in runtime with xseticon to a PNG one, it shows up.
Would be great if you include both PNG and SVG icons.

Thanks

**Comment by mthqwork** [comment] 2018-10-18 14:07
I have tested this under plasma desktop and it works fine. 

However, under MATE 1.20 and XFCE it's still default icon as described. 

I hope this will be enhanced soon :) 

Thank You

**Comment by mthqwork** [comment] 2019-01-27 22:40
@zencubic I will try to figure it also, maybe we can find a solution for it. Other apps are affected too. So maybe we are not alone.

**Comment by zencubic** [comment] 2019-01-29 10:47
IMO XFCE should support SVG icons out of the box. Maybe someone created an issue for that at XFCE. Would be a great discharge for developer of such applications. I didn't even found a documentation from XFCE in which they described where to place the icons. Maybe there's also a freedesktop standard which is responsible for this

**Comment by TimB87** [comment] 2019-06-28 18:38
I tried it with i3bar and i3bar-rust - both don't show the icon for pulseeffects. Can anybody confirm to have this working elsewhere or tell me what package I need to provide to get an taskbar icon?

**Comment by wwmm** [comment] 2020-08-15 14:42
Is this still a problem?

**Comment by TimB87** [comment] 2020-08-15 14:45
I still don't get any taskbar icon, so I'd say yes (still using [i3status-rust](https://github.com/greshake/i3status-rust))

**Comment by wwmm** [comment] 2020-08-15 14:48
I imagine that the problem is the icon being in the SVG format. But it is so odd that nowadays there are desktops that do not support SVG...

**Comment by TimB87** [comment] 2020-08-15 14:50
I would need to investigate, but I could bet my left shoe blindly that svg icons work on my setup 🤔

**Comment by TimB87** [comment] 2020-08-15 15:38
@wwmm just checked, I do run [redshift](https://github.com/jonls/redshift/tree/master/data/icons/hicolor/scalable/apps) which only provides svg icons and for that I get a taskbar icon:

![i3status-rust](https://i.imgur.com/HzbJPPQ.png)

**Comment by wwmm** [comment] 2020-08-15 16:40
So it must be something related to the SVG standard being used. Somehow GNOME shows our icon with no problem.

**Comment by wwmm** [comment] 2020-08-15 16:44
Maybe our icon is using a SVG feature that is not supported in these taskbar manages but it is on the bigger desktops. But I do not know enough about SVG to verify that.

**Comment by TimB87** [comment] 2020-08-15 21:11
I tried reading into i3status-rust and can't see that it actually handles that part of the bar for i3.. but I would need longer to actually really understand the code, so I am not 100% sure about this.

**Comment by mthqwork** [comment] 2020-08-16 01:50
As for taskbar now it's OK at me (XFCE4, Arch, still :) )
As for switcher i can't test it right now, but if I remember good, it's also working.

**Comment by mthqwork** [comment] 2020-08-18 12:31
I have checked it and it works well at the switcher too.

**Comment by wwmm** [comment] 2020-09-12 14:53
As this issue was solved in XFCE. I will close it. @TimB87 the current code in the master branch has a new icon from the Korla icon theme. If you still have problems in i3status with it feel free to open a new issue.

**Closed by wwmm** 2020-09-12 14:53 UTC
Labels: enhancement

**Comment by TimB87** [comment] 2020-09-15 19:55
@wwmm will try it out master, hopefully over the weekend. I've been swamped the past days, but if the issue persists i'll open one up to get this resolved/help with my environment that produces those problems.
