### ISSUE TITLE
webrtcdsp plugin missing

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#290] opened 2018-07-29 18:53 UTC
I remembered that since it first appeared and untill now I could not make webrtcdsp work in neither LANG=c nor ru_RU.utf-8. It's found by meson:
`Native dependency gstreamer-webrtc-1.0 found: YES 1.14.1`
The build log is attached, but it shows that it was built.
[build1.log](https://github.com/wwmm/pulseeffects/files/2239071/build1.log)

`env PULSEEFFECTS_DEBUG=1 pulseeffects` gave no output (I installed `pulseeffects-dbgsym` containing `/usr/lib/debug/.build-id/e2/18fe2a5df2fe9fad1eff76d72e177b089b3a3e.debug` and it did not change the debug output).

`webrtc.hpp` is missing on Ubuntu 18.04, it has `webrtc.h`, I tries to change the `#include`, but compilation failed.

```
user@pay2:~/Изображения$ dpkg -L libgstreamer-plugins-bad1.0-dev | grep webrtc
/usr/include/gstreamer-1.0/gst/webrtc
/usr/include/gstreamer-1.0/gst/webrtc/dtlstransport.h
/usr/include/gstreamer-1.0/gst/webrtc/icetransport.h
/usr/include/gstreamer-1.0/gst/webrtc/rtcsessiondescription.h
/usr/include/gstreamer-1.0/gst/webrtc/rtpreceiver.h
/usr/include/gstreamer-1.0/gst/webrtc/rtpsender.h
/usr/include/gstreamer-1.0/gst/webrtc/rtptransceiver.h
/usr/include/gstreamer-1.0/gst/webrtc/webrtc-enumtypes.h
/usr/include/gstreamer-1.0/gst/webrtc/webrtc.h
/usr/include/gstreamer-1.0/gst/webrtc/webrtc_fwd.h
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-webrtc-1.0.pc
/usr/lib/x86_64-linux-gnu/libgstwebrtc-1.0.so
user@pay2:~/Изображения$ cat /usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-webrtc-1.0.pc
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include/gstreamer-1.0

Name: GStreamer WebRTC
Description: GStreamer WebRTC support
Requires: gstreamer-1.0 gstreamer-base-1.0
Version: 1.14.1
Libs: -L${libdir} -lgstwebrtc-1.0
Cflags: -I${includedir}

user@pay2:~/Изображения$ ls /usr/include/gstreamer-1.0/gst/webrtc
dtlstransport.h  rtcsessiondescription.h  rtpsender.h       webrtc-enumtypes.h  webrtc.h
icetransport.h   rtpreceiver.h            rtptransceiver.h  webrtc_fwd.h
```

**Comment by mikhailnov** [comment] 2018-07-29 18:54
There is no `Webrtc` in the plugin list, I looked all other effects and none of them matches what I saw in Glade.
![deepinscreenshot_ - _20180729203835](https://user-images.githubusercontent.com/15802528/43369634-020c000e-937a-11e8-8172-e75646d7df43.png)

**Comment by mikhailnov** [comment] 2018-07-29 19:02
Does it work on Arch Linux and which files do you have in /usr/include/gstreamer-1.0/gst/webrtc?

**Comment by wwmm** [comment] 2018-07-29 19:08
It works on Arch Linux. PulseEffects offers only a wrapper to GStreamer's `webrtcdsp` just like it does with Calf plugins or the equalizer plugin. It is not built together with PE like the convolver or the crystalizer.

The first step is to check the output of `gst-inspect-1.0 webrtcdsp`. If there is nothing in the output something went wrong in the webrtcdsp installation.

this is the output of `/usr/include/gstreamer-1.0/gst/webrtc`:

```
dtlstransport.h  icetransport.h  rtcsessiondescription.h  rtpreceiver.h  rtpsender.h  rtptransceiver.h  webrtc-enumtypes.h  webrtc_fwd.h  webrtc.h
```
But as this plugin is not compiled with PE it is not relevant. The output of `ls /usr/lib/gstreamer-1.0/ | grep -i webrtc` will be more interesting:

```
libgstwebrtcdsp.so
libgstwebrtc.so
```

The libraries above are provided by `gst-plugins-bad`

**Comment by wwmm** [comment] 2018-07-29 19:11
Maybe the meson check is useless. I thought that it would help to verify if the user has the plugin installed. But it seems that this webrtc found by meson is not what I thought it was

**Comment by wwmm** [comment] 2018-07-29 19:13
I will remove the `gstreamer-webrtc-1.0` check. It seems that this is not meant for people using the plugin but the webrtc api in a lower level

**Comment by mikhailnov** [comment] 2018-07-29 19:14
https://github.com/wwmm/pulseeffects/blob/master/src/webrtc.cpp#L3 
`#include "webrtc.hpp"`
What is webrtc.hpp and where is it taken from?

>  I thought that it would help to verify if the user has the plugin installed
Only on Arch Linux where -dev packages are not separate - maybe, on Debian/Ubuntu it's libgstreamer-plugins-bad1.0-dev which provides /usr/include/gstreamer-1.0/gst/webrtc

```
$ locate libgstwebrtc
/usr/lib/x86_64-linux-gnu/libgstwebrtc-1.0.so
/usr/lib/x86_64-linux-gnu/libgstwebrtc-1.0.so.0
/usr/lib/x86_64-linux-gnu/libgstwebrtc-1.0.so.0.1401.0
/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstwebrtc.so
/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstwebrtcdsp.so
```

**Comment by mikhailnov** [comment] 2018-07-29 19:15
$ LANG=c gst-inspect-1.0 webrtcdsp
```
Factory Details:
  Rank                     none (0)
  Long-name                Voice Processor (AGC, AEC, filters, etc.)
  Klass                    Generic/Audio
  Description              Pre-processes voice with WebRTC Audio Processing Library
  Author                   Nicolas Dufresne <nicolas.dufresne@collabora.com>

Plugin Details:
  Name                     webrtcdsp
  Description              Voice pre-processing using WebRTC Audio Processing Library
  Filename                 /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstwebrtcdsp.so
  Version                  1.14.1
  License                  LGPL
  Source module            gst-plugins-bad
  Source release date      2018-05-17
  Binary package           GStreamer Bad Plugins (Ubuntu)
  Origin URL               https://launchpad.net/distros/ubuntu/+source/gst-plugins-bad1.0

GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstBaseTransform
                         +----GstAudioFilter
                               +----GstWebrtcDsp

Pad Templates:
  SRC template: 'src'
    Availability: Always
    Capabilities:
      audio/x-raw
                 format: S16LE
                 layout: interleaved
                   rate: { (int)48000, (int)32000, (int)16000, (int)8000 }
               channels: [ 1, 2147483647 ]
  
  SINK template: 'sink'
    Availability: Always
    Capabilities:
      audio/x-raw
                 format: S16LE
                 layout: interleaved
                   rate: { (int)48000, (int)32000, (int)16000, (int)8000 }
               channels: [ 1, 2147483647 ]

Element has no clocking capabilities.
Element has no URI handling capabilities.

Pads:
  SINK: 'sink'
    Pad Template: 'sink'
  SRC: 'src'
    Pad Template: 'src'

Element Properties:
  name                : The name of the object
                        flags: readable, writable
                        String. Default: "webrtcdsp0"
  parent              : The parent of the object
                        flags: readable, writable
                        Object of type "GstObject"
  qos                 : Handle Quality-of-Service events
                        flags: readable, writable
                        Boolean. Default: false
  probe               : The name of the webrtcechoprobe element that record the audio being played through loud speakers. Must be set before PAUSED state.
                        flags: readable, writable
                        String. Default: "webrtcechoprobe0"
  high-pass-filter    : Enable or disable high pass filtering
                        flags: readable, writable
                        Boolean. Default: true
  echo-cancel         : Enable or disable echo canceller
                        flags: readable, writable
                        Boolean. Default: true
  echo-suppression-level: Controls the aggressiveness of the suppressor. A higher level trades off double-talk performance for increased echo suppression.
                        flags: readable, writable
                        Enum "GstWebrtcEchoSuppressionLevel" Default: 1, "moderate"
                           (0): low              - Low Suppression
                           (1): moderate         - Moderate Suppression
                           (2): high             - high Suppression
  noise-suppression   : Enable or disable noise suppression
                        flags: readable, writable
                        Boolean. Default: true
  noise-suppression-level: Controls the aggressiveness of the suppression. Increasing the level will reduce the noise level at the expense of a higher speech distortion.
                        flags: readable, writable
                        Enum "GstWebrtcNoiseSuppressionLevel" Default: 1, "moderate"
                           (0): low              - Low Suppression
                           (1): moderate         - Moderate Suppression
                           (2): high             - High Suppression
                           (3): very-high        - Very High Suppression
  gain-control        : Enable or disable automatic digital gain control
                        flags: readable, writable
                        Boolean. Default: true
  experimental-agc    : Enable or disable experimental automatic gain control.
                        flags: readable, writable
                        Boolean. Default: false
  extended-filter     : Enable or disable the extended filter.
                        flags: readable, writable
                        Boolean. Default: true
  delay-agnostic      : Enable or disable the delay agnostic mode.
                        flags: readable, writable
                        Boolean. Default: false
  target-level-dbfs   : Sets the target peak |level| (or envelope) of the gain control in dBFS (decibels from digital full-scale).
                        flags: readable, writable
                        Integer. Range: 0 - 31 Default: 3 
  compression-gain-db : Sets the maximum |gain| the digital compression stage may apply, in dB.
                        flags: readable, writable
                        Integer. Range: 0 - 90 Default: 9 
  startup-min-volume  : At startup the experimental AGC moves the microphone volume up to |startup_min_volume| if the current microphone volume is set too low. No effect if experimental-agc isn't enabled.
                        flags: readable, writable
                        Integer. Range: 12 - 255 Default: 12 
  limiter             : When enabled, the compression stage will hard limit the signal to the target level. Otherwise, the signal will be compressed but not limited above the target level.
                        flags: readable, writable
                        Boolean. Default: true
  gain-control-mode   : Controls the mode of the compression stage
                        flags: readable, writable
                        Enum "GstWebrtcGainControlMode" Default: 1, "adaptive-digital"
                           (1): adaptive-digital - Adaptive Digital
                           (2): fixed-digital    - Fixed Digital
  voice-detection     : Enable or disable the voice activity detector
                        flags: readable, writable
                        Boolean. Default: false
  voice-detection-frame-size-ms: Sets the |size| of the frames in ms on which the VAD will operate. Larger frames will improve detection accuracy, but reduce the frequency of updates
                        flags: readable, writable
                        Integer. Range: 10 - 30 Default: 10 
  voice-detection-likelihood: Specifies the likelihood that a frame will be declared to contain voice.
                        flags: readable, writable
                        Enum "GstWebrtcVoiceDetectionLikelihood" Default: 1, "low"
                           (0): very-low         - Very Low Likelihood
                           (1): low              - Low Likelihood
                           (2): moderate         - Moderate Likelihood
                           (3): high             - High Likelihood
```

**Comment by wwmm** [comment] 2018-07-29 19:17
The plugin is there. Which blocksize do you have in the pulseaudio section  of PE settings menu? At least in my computer the webrtc is not working with a blocksize value smaller than 512. I don't know if this also happens on other hardwares

**Comment by mikhailnov** [comment] 2018-07-29 19:21
512. set 1024 and 128, restarted and got nothing new.

On your computer, it crashes with blocksize <512 or the plugin also simply does not load into the UI?

**Comment by mikhailnov** [comment] 2018-07-29 19:33
no, I don't have it...
`rm -fvr ~/.config/PulseEffects` did not help. 
Screen:
![deepinscreenshot_desktop_20180729223123](https://user-images.githubusercontent.com/15802528/43369930-24ab87c4-937f-11e8-9abf-06f8f1f5fbbf.png)

`/usr/share/glib-2.0/schemas/com.github.wwmm.pulseeffects.sourceoutputs.webrtc.gschema.xml` is there

**Comment by wwmm** [comment] 2018-07-29 19:37
I think I know what is going on. Click on the mic symbol in the top left corner fo the window. The widgets that control microphone effects are show when you click there. These widgets you see now control effects for applications output

**Comment by wwmm** [comment] 2018-07-29 19:38
This way you can have different equalizer settings for mic and app output for example

**Comment by mikhailnov** [comment] 2018-07-29 19:50
Oh, it's there. Thank you. I forgot about it, now I remembered that I have already found it in output effects before. 

I get SIGTRAP in some time after `strace pulseeffects`, 100% reproducible even if I do nothing. Everything is OK without strace. Is it a problem?
 
```
(pulseeffects:21479): pulseeffects-ERROR **: 22:40:36.498: pulse_manager: context event subscribe failed!
+++ killed by SIGTRAP +++
Ловушка трассировки/останова
```

**Comment by wwmm** [comment] 2018-07-29 19:54
Almost nothing will work after a `context event subscribe failed!`. So I'd say that is a very serious issue.

But at least under normal operations I do not see this. Any reason to run it under strace? Also after how much time the crash happens? I have just installed strace here and it seems fine

**Comment by wwmm** [comment] 2018-07-29 19:56
If it only happens with strace I would not be worried. But up to now I can't reproduce this here with or without strace

**Comment by mikhailnov** [comment] 2018-07-29 20:00
$ time strace pulseeffects
<...>
(pulseeffects:23182): pulseeffects-ERROR **: 23:00:20.100: pulse_manager: context event subscribe failed!
 <unfinished ...>) = ?
+++ killed by SIGTRAP +++
Ловушка трассировки/останова

real	0m30,505s
user	0m7,005s
sys	0m0,984s

**Comment by mikhailnov** [comment] 2018-07-29 20:03
Only with strace

**Comment by wwmm** [comment] 2018-07-29 20:07
I can only reproduce this here if I use `strace` together with `time`. With strace alone I do not have crash.

My guess is that these commands are messing with Pulseaudio communications timing.

I would not bother with this

**Comment by mikhailnov** [comment] 2018-07-29 20:09
On my system it's reproducible both with and without time

**Comment by mikhailnov** [comment] 2018-07-29 20:09
I noticed it accidently because I wanted to find webrtc in strace

**Comment by wwmm** [comment] 2018-07-29 20:12
Ok. Considering that I communicate with pulseaudio through a background thread timing interference is probably the cause. I never saw this under normal circumstances.

In any case as the original issue is solved we can close this.

**Closed by wwmm** 2018-07-29 20:12 UTC
