### ISSUE TITLE
[Feature Request] Support minimizing to systray

### ISSUE THREAD

**Issue by spstarr** [wwmm/pulseeffects#300] opened 2018-08-14 22:03 UTC
It would be great if we could minimize to system tray in KDE/GNOME environments.

Thanks for this program!

**Comment by wwmm** [comment] 2018-08-14 23:11
Hi! Last year a few users asked for this. It was not implemented because GTK 4 will not support systray. So we would have to remove it when when porting PulseEffects from GTK3 to GTK4.

At least at that time what users really wanted was to have PulseEffects running in background after closing its window. If that is what you want you can switch on `Start Service at Login`
![screenshot from 2018-08-14 20-05-48](https://user-images.githubusercontent.com/16225172/44123291-fa4a6b54-9ffd-11e8-8ef1-c03e06b6e8ab.png)
After a logout you will be able to close the window without losing the effects. In case you do not want to logout you can use the option `--gapplication-service` described at [Command-Line-Options](https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options)

**Closed** 2018-08-21 20:00 UTC
Labels: wontfix

**Comment by smac89** [comment] 2019-04-19 02:29
If anyone is running gnome, you can use this gnome [extension](https://extensions.gnome.org/extension/1750/minimize-to-tray/) to minimize the window to the system tray

**Comment by csehszlovakze** [comment] 2019-05-09 16:11
Systray would be awesome because we could switch profiles from there (theoretically of course). I frequently swap profiles (music, youtube videos, movies, total bass cut before I sleep) so it'd improve my usage of the app.

I know what the issue is with gtk4, but that could "easily" be fixed with branching and still maintaining a gtk3 version, especially for those of us who don't even use Gnome 3.

**Comment by wwmm** [comment] 2019-05-09 16:31
Switching profiles is probably the feature that would benefit the most from a tray icon. And if someone in the community is willing to fork the repository and maintain a gtk3 version with tray icons it is fine for me. I have no objections. But as PE is mostly a one man job I'd like to keep my life as simple as possible. I do not have time to maintain 2 versions or to backport features to an eventual gtk3 branch. My focus will be entirely in the GTK4 version.
