### ISSUE TITLE
All effects in pulseaudio effects stopped working suddenly

### ISSUE THREAD

**Issue by OmegaDarkMage** [wwmm/pulseeffects#643] opened 2020-03-23 23:05 UTC
After booting into my PC today I am unable to get any effects in pulseaudio working. I ended up uninstalling it and then trying to reinstall it but for some reason I can't get it to reinstall from the terminal. I get this in the terminal when trying to install,Reading package lists... Done
Building dependency tree       
Reading state information... Done
pulseaudio is already the newest version (1:12.2-9~bionic1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pulseeffects : Depends: libstdc++6 (>= 9) but 8.3.0-26ubuntu1~18.04 is to be installed
                Recommends: gstreamer1.0-convolver-pulseeffects but it is not going to be installed
                Recommends: gstreamer1.0-crystalizer-pulseeffects but it is not going to be installed
                Recommends: gstreamer1.0-autogain-pulseeffects but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I'm currently on Linux Mint 19 if that helps.

**Comment by wwmm** [comment] 2020-03-23 23:14
Any ideas @mikhailnov ?

**Comment by vmannarelli** [comment] 2020-03-24 00:45
a mi tambien me aparece este error para poder actualizar a la ultima version de pulseeffects:
pulseeffects : Depends: libstdc++6 (>= 9) but 8.3.0-26ubuntu1~18.04 is to be installed

**Comment by OmegaDarkMage** [comment] 2020-03-24 03:19
Using the flatpak version for now, it seems to work with no issues.

**Comment by vmannarelli** [comment] 2020-03-24 06:34
what is the flatpak version?

**Comment by mikhailnov** [comment] 2020-03-24 09:09
> pulseeffects : Depends: libstdc++6 (>= 9) but 8.3.0-26ubuntu1~18.04 is to be installed

It will be solved, pulseeffects 4.7.2-3~bionic2 is being built to solve this. Sorry.

As for the original issue with effects, may be it is a duplicate of https://github.com/wwmm/pulseeffects/issues/641 , try with pulseeffects 4.7.2 when it becomes installable

**Comment by OmegaDarkMage** [comment] 2020-03-24 09:13
@vmannarelli The flatpak version is usually available in the software manager.

**Comment by OmegaDarkMage** [comment] 2020-03-24 09:15
@mikhailnov No worries and thank you for your hard work on this project.

**Comment by vmannarelli** [comment] 2020-03-24 14:07
> > pulseeffects : Depends: libstdc++6 (>= 9) but 8.3.0-26ubuntu1~18.04 is to be installed
> 
> It will be solved, pulseeffects 4.7.2-3~bionic2 is being built to solve this. Sorry.
> 
> As for the original issue with effects, may be it is a duplicate of #641 , try with pulseeffects 4.7.2 when it becomes installable

Thanks ... update and everything was corrected ... thanks for the great equalizer!

**Closed** 2020-03-27 04:20 UTC
