### ISSUE TITLE
Void Linux GLib-GIO-ERROR / python errors

### ISSUE THREAD

**Issue by cr6git** [wwmm/pulseeffects#22] opened 2017-06-06 14:49 UTC
Hi @wwmm ! 

I am trying to build a package for Void linux, in response to this recent [PackageRequest](https://github.com/voidlinux/void-packages/issues/6557). 

I'm almost done, but I get this error when I run the program: 

`$ pulseeffects`
`(pulseeffects:17538): GLib-GIO-ERROR **: Settings schema 'com.github.wwmm.pulseeffects' is not installed`
`Trace/breakpoint trap`

Do you have any idea ? 
Regards.

**Comment by wwmm** [comment] 2017-06-06 17:13
Hi

After copying the files and folders in pulseeffects `share` folder to `/usr/share` you have to run  `glib-compile-schemas /usr/share/glib-2.0/schemas/`. The setup.py script does not does that as setupytools documentation does not recommends this to be done there

**Comment by cr6git** [comment] 2017-06-06 19:28
OK, I added that, but now I get this error: 

`PulseEffects - CRITICAL - failed to start pulseaudio context`

It sounds like a problem with pulseaudio? I don't know much about it...

**Comment by wwmm** [comment] 2017-06-06 19:49
hummm... Which version of pulseaudio do you have? Is there anything else in the system's log when this happen?

**Comment by cr6git** [comment] 2017-06-06 20:12
In Void linux we have pulseaudio 10.0 

`$ pulseeffects`
`GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.`
`22:01:11.429 - PulseEffects - CRITICAL - failed to start pulseaudio context`
`^CTraceback (most recent call last):`
`  File "/usr/bin/pulseeffects", line 6, in <module>`
`    a = Application()`
`  File "/usr/lib/python3.5/site-packages/PulseEffects/application.py", line 49, in __init__`
`    self.pm = PulseManager()`
`  File "/usr/lib/python3.5/site-packages/PulseEffects/pulse_manager.py", line 65, in __init__`
`    while self.context_ok is False:`
`KeyboardInterrupt`

Well, there is an _obvious problem_ with pulseaudio on my system: 

`$ start-pulseaudio-x11`
`Connection failure: Connection refused`
`pa_context_connect() failed: Connection refused`

**Comment by cr6git** [comment] 2017-06-06 21:30
The problem with pulseaudio is solved ! 
My system is now _correctly_ configured... 
...but it looks like errors with Python: 

`$ pulseeffects`
`Traceback (most recent call last):`
`  File "/usr/bin/pulseeffects", line 4, in <module>`
`    from PulseEffects.application import Application`
`  File "/usr/lib/python3.5/site-packages/PulseEffects/application.py", line 10, in <module>`
`    from PulseEffects.gst import GstEffects`
`  File "/usr/lib/python3.5/site-packages/PulseEffects/gst.py", line 7, in <module>`
`    from gi.repository import GObject, Gst`
`  File "/usr/lib/python3.5/site-packages/gi/importer.py", line 146, in load_module`
`    dynamic_module = load_overrides(introspection_module)`
`  File "/usr/lib/python3.5/site-packages/gi/overrides/__init__.py", line 125, in load_overrides`
`    override_mod = importlib.import_module(override_package_name)`
`  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module`
`    return _bootstrap._gcd_import(name[level:], package, level)`
`  File "/usr/lib/python3.5/site-packages/gi/overrides/Gst.py", line 487, in <module>`
`    from . import _gi_gst`
`ImportError: Error relocating /usr/lib/python3.5/site-packages/gi/overrides/_gi_gst.cpython-35m-x86_64-linux-gnu.so: Py_InitModule4_64: symbol not found`

**Comment by wwmm** [comment] 2017-06-06 22:44
It seems there is a problem with gst-python. Which version do you have?

**Comment by cr6git** [comment] 2017-06-08 16:31
gst1-python3 version 1.12.0

**Comment by wwmm** [comment] 2017-06-08 17:37
This is very strange. I have gst-python 1.12 in Arch Linux too and I do not have the error `Py_InitModule4_64: symbol not found`. Maybe the problem is with the python version. Here in Arch I have python 3.6.1. BAsed on your error logs you are probably wi python 3.5. I think this version should be ok but I do not remember If I had the chance to test PulseEffects with python 3.5

**Comment by thenewnano** [comment] 2017-06-26 19:24
I had something similiar, deleted the scheme xml file, then run compile-schemas and after that copied the files again into /usr/share and did run the compile-schemas again, it resolved wrong schemes being compiled from the previous version.

**Comment by wwmm** [comment] 2017-09-27 15:53
As this problem is specific to void linux packages and there is nothing I can do about it I will close this issue.

**Closed by wwmm** 2017-09-27 15:53 UTC

**Comment by cr6git** [comment] 2017-11-29 15:08
Today, tried to create a package for the latest release `pulseeffects-3.0.9` but I got this error: 
````
$ /usr/bin/pulseeffects
Traceback (most recent call last):
  File "/usr/bin/pulseeffects", line 6, in <module>
    from PulseEffects.application import Application
  File "/usr/lib/python3.6/site-packages/PulseEffects/application.py", line 12, in <module>
    from PulseEffects.sink_input_effects import SinkInputEffects
  File "/usr/lib/python3.6/site-packages/PulseEffects/sink_input_effects.py", line 6, in <module>
    gi.require_version('GstInsertBin', '1.0')
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GstInsertBin not available
````

`gstreamer` is installed: 
````
$ xbps-query -s gst
[*] gst-plugins-bad1-1.12.3_2  GStreamer plugins from the bad set (v1.x)
[*] gst-plugins-base1-1.12.3_1 GStreamer Base Plug-ins (v1.x)
[*] gst-plugins-good1-1.12.3_1 GStreamer set of well-maintained good plug-ins (1.x)
[*] gst1-python3-1.12.3_1      Python3 bindings for GStreamer 1.x
[*] gstreamer1-1.12.3_1        Core GStreamer libraries and elements (1.x)
````

Which package is missing ?? Thanks.

**Comment by wwmm** [comment] 2017-11-29 15:33
GstInsertBin is from gst-plugins-bad. Try to see if there is more gst-plugins-bad packages in void repositories

**Comment by cr6git** [comment] 2017-11-29 17:58
We have only these packages: 
````
[-] gst-plugins-bad-0.10.23_23       GStreamer plugins from the bad set
[-] gst-plugins-bad-devel-0.10.23_23 GStreamer plugins from the bad set - development files
[*] gst-plugins-bad1-1.12.3_2        GStreamer plugins from the bad set (v1.x)
[-] gst-plugins-bad1-devel-1.12.3_2  GStreamer plugins from the bad set (v1.x) - development files
````

In package `gst-plugins-bad1` we have: 
````
/usr/lib/libgstinsertbin-1.0.so.0.1203.0
/usr/lib/libgstinsertbin-1.0.so.0 -> /usr/lib/libgstinsertbin-1.0.so.0.1203.0
````

I can't find `GstInsertBin`.

**Comment by wwmm** [comment] 2017-11-30 00:06
Maybe the problems are in the python bindings. Dou you have the file `/usr/share/gir-1.0/GstInsertBin-1.0.gir` in your system? I think the namespace `GstInsertBin` is defined in it.

**Comment by cr6git** [comment] 2017-12-01 09:50
I'm almost done, but it seems like something is still missing... 
When I run the program: 
````
$ pulseeffects
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
10:40:33.19 - PulseEffects - CRITICAL - failed to start pulseaudio context
10:40:33.20 - PulseEffects - INFO - unferencing pulseaudio context object
^CKilled
````
nothing appears... and I have to kill `python3` to stop the process.

**Comment by wwmm** [comment] 2017-12-01 10:51
Nothing will work after a pulseaudio context failure. Something is not right in your pulseaudio installation. Is it running? Do you have libpulse installed?

**Comment by cr6git** [comment] 2017-12-01 11:40
You're right @wwmm ! `pulseaudio` was not correctly configured... 

According to our wiki: [PulseAudio#Recommended_setup](https://wiki.voidlinux.eu/PulseAudio#Recommended_setup): I had to install & enable `dbus`, `consolekit` and `cgmanager` services to be able to run `pulseeffects`. 

THANK YOU.
