### ISSUE TITLE
PulseEffects closing with SIGKILL after losing focus

### ISSUE THREAD

**Issue by mthqwork** [wwmm/pulseeffects#950] opened 2021-04-16 11:27 UTC
Hi, i have a strange issue.
If i start PulseEffects, and switch workspace it works, it may crash later.
But if i click to another window, as soon as PE loses focus, it stops with SIGKILL, no core dump generated.

Arch with latest packages as of today, PE version 5.0.3-1, from Arch repo.
DE: XFCE 4

[messages.txt](https://github.com/wwmm/pulseeffects/files/6324547/messages.txt)
[pactl_list_sink_inputs.txt](https://github.com/wwmm/pulseeffects/files/6324563/pactl_list_sink_inputs.txt)
[pactl_list_sinks.txt](https://github.com/wwmm/pulseeffects/files/6324564/pactl_list_sinks.txt)
[pactl_list_sources.txt](https://github.com/wwmm/pulseeffects/files/6324567/pactl_list_sources.txt)
pactl list-source-outputs was returned without output.
[pesettings.txt](https://github.com/wwmm/pulseeffects/files/6324590/pesettings.txt)

As I'm running pipewire, i cant attach pulseaudio --dump-conf.

Thanks in advance.

**Comment by mthqwork** [comment] 2021-04-16 11:31
[
[pesettings.txt](https://github.com/wwmm/pulseeffects/files/6324589/pesettings.txt)
](url)

**Comment by wwmm** [comment] 2021-04-16 14:39
Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Maybe something interesting will be printed in the terminal.

In my online classes I have been using PulseEffects with its window opened in another desktop also on Arch Linux. At least in Gnome 3 and Gnome 40 this did not cause a sigkill. Maybe gtk is interacting differently with xfce.

**Comment by mthqwork** [comment] 2021-04-16 15:06
Yep, I have tried that, You can see the output in messages.txt. Nothing interesting is there, i think. Tried it sometimes, but nothing is printed before it gets killed.

**Comment by wwmm** [comment] 2021-04-16 15:51
Sorry. I just assumed that the messages file was something else. Try to disable the realtime priority in our settings menu. I do not know why yet but trying to use realtime in the GStreamer playback thread is leading to sigkill in some situations.

**Comment by mthqwork** [comment] 2021-04-17 17:31
Thanks! I have tested it quickly, looks like that flipping it to "Niceness" from "Real time" solved it. I will get back to You with the long-term results :)

**Comment by wwmm** [comment] 2021-04-17 18:28
Something must have change in one of the low level system libraries. I have no idea about what it could have been. Fortunately it is not going to be a concern when the gtk4 branch is ready. As PipeWire filters are replacing GStreamer in this branch realtime priorities will be handled by PipeWire. I won't have to do this myself anymore.

**Comment by awilliamson** [comment] 2021-04-18 11:44
> Thanks! I have tested it quickly, looks like that flipping it to "Niceness" from "Real time" solved it. I will get back to You with the long-term results :)

This worked for me too. Had the exact same SIGKILL on focus loss. Nothing useful error message wise apart from that.

**Comment by mthqwork** [comment] 2021-04-20 14:22
At my home PC, running the exact same Arch it wont happens. Running fine with realtime prio. Strange.

**Comment by MartinX3** [comment] 2021-05-11 19:42
Here the same happens

**Comment by chezbgone** [comment] 2021-05-20 22:57
Looks like a duplicate of #913.

**Comment by wwmm** [comment] 2021-05-21 14:11
>Looks like a duplicate of #913.

Yes. Let's close this one.

**Closed by wwmm** 2021-05-21 14:11 UTC
