### ISSUE TITLE
Saving a profile always stores the settings as of starting PulseEffects

### ISSUE THREAD

**Issue by ferreum** [wwmm/pulseeffects#379] opened 2018-11-20 18:50 UTC
1. Start PulseEffects
2. Open the profiles drop-down and save a new profile or overwrite one
3. Change some equalizer settings
4. Save or overwrite another profile in the drop-down

Both profiles now contain the same settings - whatever was set when starting PulseEffects. Both profile files in `~/.config/PulseEffects` contain the same data.

I expected this to save the settings that were currently seen in PulseEffects.

As a workaround I need to restart PulseEffects before saving a profile.

PulseEffects version: 4.4.0
Environment: Arch Linux, i3 window manager

**Comment by wwmm** [comment] 2018-11-20 19:02
I cannot reproduce this here on Arch Linux ( GNOME ). Did you ever executed PulseEffects as root? It may be a permission problem when accessing the dconf database. What is printed in the terminal when you execute PulseEffects in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects` and tries to save or load a preset?

**Comment by ferreum** [comment] 2018-11-20 19:21
On every load/save it just prints a single message:
```
(pulseeffects:9587): pulseeffects-DEBUG: 20:15:33.335: presets_manager: saved preset: /home/daniel/.config/PulseEffects/test2.json
(pulseeffects:9587): pulseeffects-DEBUG: 20:16:10.255: presets_manager: loaded preset: /home/daniel/.config/PulseEffects/test2.json
```
Also, in `dconf-editor` I can see the current settings update immediately when changing anything in PulseEffects.
Could this be related to gnome not running for me? Seems strange as dconf seems to reflect the settings just fine.

**Comment by ferreum** [comment] 2018-11-20 19:45
Yes, they are definitely equal, as reloading them results in the same state, and I compared them with vimdiff/diff.

Though, just trying your instructions, I noticed that it works fine when starting it from a terminal (sorry - I didn't notice this when you instructed me to start it with an envar).

Previously I always started PulseEffects with via rofi, which in turn I ran via a shortcut in i3. When starting it like this, the behavior is as I described.

So I suspect that there is an environment issue at play. One candidate may be this one: `XDG_RUNTIME_DIR=/run/user/1000`, which is not set when I start it via i3/rofi.

**Comment by wwmm** [comment] 2018-11-20 20:36
No problems. It is good to know you found a solution. The down side is that it doesn't make sense to add this kind of workaround to PulseEffects as it is a very specific use case. I suggest you report this environment variable issue to rofi's developers.

I will close this issue. In case additional problems happen feel free to reopen or to open another one

**Closed by wwmm** 2018-11-20 20:36 UTC
