### ISSUE TITLE
After some time, audio stops working entirely forcing me to kill PusleEffects in order to restart the audio service

### ISSUE THREAD

**Issue by I-Iawk** [wwmm/pulseeffects#497] opened 2019-04-25 08:50 UTC
As per subject. 

Running Fedora 30. flatpak or the fedora repo, the result is the same.

Took me forever to replicate this...

Here's a link the [debug log](https://pastebin.com/fDSKuNW0)

After quitting pulseeffects, I was able to get the sound back:

```
$ pulseeffects -q

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.534: limiter plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.534: compressor plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.535: filter plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.535: equalizer plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.535: reverb plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.535: bass_enhancer plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.536: exciter plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.536: crossfeed plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.538: multiband_compressor plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.538: loudness plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.539: gate plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.543: multiband_gate plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.543: deesser plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.544: stereo_tools plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.554: delay plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.566: limiter plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.566: compressor plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.567: filter plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.567: equalizer plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.567: reverb plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.567: gate plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.568: deesser plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.569: webrtc plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.569: multiband_compressor plugin was not found!

(pulseeffects:20444): pulseeffects-WARNING **: 01:41:32.570: multiband_gate plugin was not found!
```

Thoughts?

**Comment by wwmm** [comment] 2019-04-25 15:00
Your log has errors like `GLib-GIO-WARNING **: 01:10:11.744: g_settings_set_value: value for key 'band0-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range` that should not be there. Try to reset PulseEffects config `pulseeffects --reset`.

I also see `presets_manager: loaded preset: /root/.config/PulseEffects/output/Perfect EQ.json`. Are you running PulseEffects as root user? I don't think it is a good idea.

And for some reason that is not clear the convolver is reinitializing multiples times. This is probably what made the audio stop. Weird.

It is not the first time fedora users come here with bizarre problems. There is something different in fedora the is causing these issues. But I still have no idea about what it could be.

**Comment by I-Iawk** [comment] 2019-04-25 19:16
> Try to reset PulseEffects config pulseeffects --reset.

I've reset this prior to testing in most cases. The result is sadly the same regardless of flatpak or fedora.

> I also see presets_manager: loaded preset: /root/.config/PulseEffects/output/Perfect EQ.json. Are you running PulseEffects as root user? I don't think it is a good idea.

I deliberately ran this as root to rule out to see if it had anything to do with permissions.

I guess I'll have to switch back to the flatpak version for the time being so I can get at least system-wide eq... Shame since I would lose out on the theming via GTK.

**Comment by jeffshee** [comment] 2019-04-26 02:24
Similar issue here, with Fedora 29, using Flatpak, pulseeffects 4.5.9
Reset after upgrade, not a new issue actually

Log attached below. 
log01 show pulseeffects failed to start when there is no playback at the background. 
log02 show pulseeffects failed to start when there is playback at the background. 
log03 show pulseeffects crashed when player go to the next/previous video/music.

Actually the log files seem pretty normal to me, there's no warning or error tag. I don't know if I missed a flag or something else when I capture the log. If so, please advice and I will capture a new one again.

`G_MESSAGES_DEBUG=pulseeffects flatpak run com.github.wwmm.pulseeffects | tee -a log` is the command I used for logging, is this correct?

[log01.txt](https://github.com/wwmm/pulseeffects/files/3119445/log01.txt)
[log02.txt](https://github.com/wwmm/pulseeffects/files/3119446/log02.txt)
[log03.txt](https://github.com/wwmm/pulseeffects/files/3119447/log03.txt)

**Comment by wwmm** [comment] 2019-04-26 04:12
Indeed the logs are normal. But in the third files it seems PulseEffects pipeline was alternating a lot between the playing and the paused state. But it is not clear if it was because the audio app was actually doing or if it is for some other reason.

**Comment by ShrewdSpirit** [comment] 2019-05-26 12:29
Exact same issue. I'm using Manjaro and when I play something, PE randomly freezes and I should kill it from task manager and open again so I get audio back.
Also I get a few stutters when I start playing something or skip the track

**Comment by wwmm** [comment] 2019-05-26 14:16
And how are your logs? Based on the ones above this issue can happen for different reasons. And I still can't reproduce it in my computer.

**Comment by wwmm** [comment] 2019-05-26 14:26
@ShrewdSpirit could you record a video of the stutters happening?

**Comment by ShrewdSpirit** [comment] 2019-05-28 09:13
@wwmm I was trying to reproduce it yesterday and it never happened! Sometimes PE freezes after play/pause or playing audio from different sources in general and sometimes it works a whole day without freezing

Here are my logs:
[log1](https://pastebin.com/qsnQzGkZ)
[log2](https://pastebin.com/kyCxAare)
[log3](https://pastebin.com/5gWsBecX)
[log4](https://pastebin.com/TQDfPJJ8)

and my [settings](https://pastebin.com/fiSQ13bm)

And here is my audio sample which stutters if I play, pause or skip the song in any player
[audio_2019-05-28_13-38-01.zip](https://github.com/wwmm/pulseeffects/files/3226582/audio_2019-05-28_13-38-01.zip)

**Comment by wwmm** [comment] 2019-05-28 15:22
It would also be good to see what PE prints when running in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Do the stutters happen when you `play, pause or skip` while two applications are playing audio at the same time? I ask because when only one audio app is playing and this app pauses for some reason PulseEffects will pause its pipeline in order to save CPU power. Otherwise we will play silence and wast resources. If you have two apps playing PE will keep its pipeline running. Even if one of them is muted. Maybe the stutters are happening hwne our piepeline is restarted.

**Comment by ShrewdSpirit** [comment] 2019-05-28 20:59
G_MESSAGES_DEBUG=pulseeffects pulseeffects gave no output except a few glib warnings and returned to shell

**Comment by wwmm** [comment] 2019-05-28 21:01
You probably had another PE instance running in background. Try to kill it first `pulseeffects -q`

**Comment by wwmm** [comment] 2019-05-28 21:03
By the way I have been doing some changes that may help with the stuttering when skipping tracks. Are you able to install PE compiling the code in master branch? At least on Arch Linux there is a `pulseeffects-git` package that will do that.

**Comment by ShrewdSpirit** [comment] 2019-05-28 21:06
sure I'll update the package and try reproducing it

**Comment by ShrewdSpirit** [comment] 2019-05-29 13:30
@wwmm I got more stutters with the update even while playing. I assume PE uses more CPU now. But the random crashes seem to be gone

**Comment by wwmm** [comment] 2019-05-29 14:23
That is bizarre. The main change compared to the oldest PE versions is that we restart our pipeline less often now. In order to save cpu power we monitor if there are applications playing audio. If there aren't we stop our pipeline. Otherwise it will play silence and waste cpu. The problem with the older PE versions is that they restart our pipeline too often. Consider that you have only one audio app running like lollypop. In this case whenever this app alternates between play/pause older PE versions will alternate its pipeline state between play/pause the same number of times. This is a issue because most audio app restart their audio stream whenever they skip tracks. As restarting our pipeline has a cost this resulted in a undesirable additional delay between tracks. In some video players like mpv they may alternate between play/pause hundreds of times when syncing audio and video like you can see here #504. 

What I am doing now is using a timeout of 5 seconds. If during this time window there is no app playing audio we stop our pipeline. This way apps like mpv can alternate state how many times they wish without causing unnecessary restarts in PE pipeline. And the way we stop now is less aggressive than before. Because of some problems we used to have in the past I have been stopping our GStreamer pipeline by putting it in the `GST_STATE_READY` state that will free some resources that would have to be reallocated again the next time the pipeline had to play. Now I just put it in the `GST_STATE_PAUSED` state that should not force reallocations.

In my tests things are smoother now. That is why I thought it would remove your stuttering. But it seems that their source is somewhere else.

**Comment by wwmm** [comment] 2019-05-29 14:30
In your Pulseaudio logs I see lots of `(audio_device_pulse_linux.cc:1705): paOperation NULL in WaitForOperationCompletion`. I do not remember having seen this kind of error before in a Pulseaudio log and we do wait for Pulseaudio operations a lot in PE. But It is not clear if they are related to a stuttering or not.

**Comment by wwmm** [comment] 2019-05-29 14:35
Oh... These messages are in discord log and not Pulseaudio... In any case it is related to audio and it is strange that they are flooding the logs with this kind of error.

**Comment by ShrewdSpirit** [comment] 2019-05-29 16:24
I just restarted my system and the stutters are vanished but before I restart, there were 4,5 AudioIPC server applications in PE coming from Firefox while I had nothing playing in Firefox but the tabs were open. Not sure if it's relevant to stutters since I reopened all those tabs with same amount of AudioIPC server applications and got not as many stutters as before.
Also FYI I'm monitoring my output devices on input (for recording reasons) not sure if it's affecting PE

**Comment by ShrewdSpirit** [comment] 2019-05-29 16:26
Also the multiband compressor and bass enhancer change their icon to warning most of the time. I guess it's because my settings are higher than PE's expectation but the output is clear and smooth

**Comment by wwmm** [comment] 2019-05-30 00:27
I imagine Firefox created those streams for a reason. And it is probably going to create again. This shouldn't be a problem.

Unless Pulseaudio has some kind of bug I am not aware of recording your output devices while using PE shouldn't be a problem.

Plugins show an warning icon when the signal arriving at their input is too strong. A saturated input can generate noises because of audio clipping https://en.wikipedia.org/wiki/Clipping_(audio). If they will be noticeable or not depends on how severe is the clipping.

**Comment by ShrewdSpirit** [comment] 2019-05-30 11:36
Thanks.

I guess the crash is solved now on master branch

**Comment by wwmm** [comment] 2019-05-30 14:56
Considering that problem of each user here seems to have a different source I think that it is best to close this issue. Feel free to open another one in case this situation still happens in PE `4.6.2` or newer

**Closed by wwmm** 2019-05-30 14:56 UTC
