### ISSUE TITLE
undefined symbol: Py_InitModule4_64

### ISSUE THREAD

**Issue by Epictek** [wwmm/pulseeffects#50] opened 2017-08-09 06:59 UTC
```
Traceback (most recent call last):
  File "/usr/bin/pulseeffects", line 4, in <module>
    from PulseEffects.application import Application
  File "/usr/lib/python3.5/site-packages/PulseEffects/application.py", line 18, in <module>
    from PulseEffects.sink_input_effects import SinkInputEffects
  File "/usr/lib/python3.5/site-packages/PulseEffects/sink_input_effects.py", line 9, in <module>
    from gi.repository import GObject, Gst
  File "/usr/lib/python3.5/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.5/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Gst.py", line 487, in <module>
    from . import _gi_gst
ImportError: /usr/lib/python3.5/site-packages/gi/overrides/_gi_gst.cpython-35m-x86_64-linux-gnu.so: undefined symbol: Py_InitModule4_64
```
Distro is Void Linux

**Comment by wwmm** [comment] 2017-08-09 15:40
Duplicate of #22

**Closed by wwmm** 2017-08-09 15:40 UTC
