### ISSUE TITLE
Version 4.8.2 kills sound when activated in Arch Linux

### ISSUE THREAD

**Issue by PDXUser** [wwmm/pulseeffects#846] opened 2020-12-03 04:54 UTC
Kernel: 5.9.11-arch2-1 x86_64 
Audio:     Device-1: Intel 6 Series/C200 Series Family High Definition Audio driver: snd_hda_intel 
           Sound Server: ALSA v: k5.9.11-arch2-1 

pulseaudio --version
pulseaudio 14.0

This seems to have happened recently.  
I am not sure what the cause would be - I did try both the stable and Git version to see if this would help.  It did not.

**Comment by M0Rf30** [comment] 2020-12-03 15:33
It is caused by the introduction of pipewire packages and pulseaudio replacement. Same issue here with pipewire enabled

**Comment by wwmm** [comment] 2020-12-03 16:03
Honestly I think it is too soon for people to make this move to Pipewire... I will update my Arch Linux install and see what happens...

**Comment by M0Rf30** [comment] 2020-12-03 16:06
@wwmm pay attention on pipewire failures, maybe you are required to install xdg-portal package for gtk

**Comment by M0Rf30** [comment] 2020-12-03 16:07
@PDXUser could you please run ```pactl info``` ?
There should be the string pipewire

**Comment by wwmm** [comment] 2020-12-03 16:16
>maybe you are required to install xdg-portal package for gtk

Why?

>could you please run pactl info

How did you install pactl? pacman forced me to uninstall Pulseaudio in order to install Pipewire. I do not have Pulseaudio utilities anymore...

In any case I have already seen the source of the problem and it is going to take a while to fix. Pipewire does not seem to have null sinks. Or its wrapper around the Pulseaudio command that loads them is in a bad state.

**Comment by wwmm** [comment] 2020-12-03 16:18
It seems to me that we will have to rewrite PulseEffects for Pipewire. This talk about being a "drop-in replacement" won't work for everybody...

**Comment by Digitalone1** [comment] 2020-12-03 16:44
Okay, I will not update to pipewire-pulse. I love Arch Linux, but this changes have no sense if they break the system.

**Comment by Digitalone1** [comment] 2020-12-03 16:47
> It seems to me that we will have to rewrite PulseEffects for Pipewire. This talk about being a "drop-in replacement" won't work for everybody...

Is this something big? Maybe we should consider to release 4.8.3 as a last version for Pulseaudio? We made lots of changes and improvements from 4.8.2.

**Comment by wwmm** [comment] 2020-12-03 17:38
>but this changes have no sense if they break the system.

MPV works and probably the other video and audio players too.

>Is this something big?

Yes. I doubt the approach used to redirect applications input/output in Pulseaudio will work in Pipewire. Probably we will have to replace all Pulseaudio code by Pipewire code as well as finding out how to process apps input/output in Pipewire. I have no idea about how this is supposed to be done there.

>Maybe we should consider to release 4.8.3 as a last version for Pulseaudio?

`4.8.3` will be released for Pulseaudio. If it is going to be the last it is hard to say.

**Comment by M0Rf30** [comment] 2020-12-03 17:47
@wwmm pactl is included in libpulse, not pulseaudio package. I don't think should be difficult to integrate with pipewire, because pipewire-pulse natively allow pulseaudio clients. I'm supposing on what I've undestood during this day fighting with pipewire

**Comment by wwmm** [comment] 2020-12-03 17:49
>pactl is included in libpulse, not pulseaudio package

Ok. The one that is missing is pacmd and not pactl.

**Comment by M0Rf30** [comment] 2020-12-03 17:51
Now I'm seeing a strange behaviour. If I launch pulseeffects it gives me a strange error. That's caused by libpulse I suppose
```
fish: 'pulseeffects' terminated by signal SIGSEGV (Address boundary error)

```

mprotect(0x7fc7b09d1000, 4096, PROT_READ) = 0
rt_sigaction(SIGSEGV, {sa_handler=0x7fc7b3e73d60, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fc7b39ec0f0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fc7b39ec0f0}, 8) = 0
futex(0x7fc7b5314068, FUTEX_WAKE_PRIVATE, 2147483647) = 0
rt_sigaction(SIGSEGV, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fc7b39ec0f0}, NULL, 8) = 0
stat("/usr/lib/gstreamer-1.0/libgstpeadapter.so", {st_mode=S_IFREG|0755, st_size=22440, ...}) = 0
stat("/usr/lib/gstreamer-1.0/libgstpeadapter.so", {st_mode=S_IFREG|0755, st_size=22440, ...}) = 0
openat(AT_FDCWD, "/usr/lib/gstreamer-1.0/libgstpeadapter.so", O_RDONLY|O_CLOEXEC) = 18
read(18, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0  \0\0\0\0\0\0"..., 832) = 832
fstat(18, {st_mode=S_IFREG|0755, st_size=22440, ...}) = 0
mmap(NULL, 24800, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 18, 0) = 0x7fc7b09c3000
mmap(0x7fc7b09c5000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 18, 0x2000) = 0x7fc7b09c5000
mmap(0x7fc7b09c7000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 18, 0x4000) = 0x7fc7b09c7000
mmap(0x7fc7b09c8000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 18, 0x4000) = 0x7fc7b09c8000
close(18)                               = 0
mprotect(0x7fc7b09c8000, 4096, PROT_READ) = 0
rt_sigaction(SIGSEGV, {sa_handler=0x7fc7b3e73d60, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fc7b39ec0f0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fc7b39ec0f0}, 8) = 0
futex(0x7fc7b5314068, FUTEX_WAKE_PRIVATE, 2147483647) = 0
rt_sigaction(SIGSEGV, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fc7b39ec0f0}, NULL, 8) = 0
futex(0x7fc7b5314068, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fc7b5314068, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fc7b5314068, FUTEX_WAKE_PRIVATE, 2147483647) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x58} ---
+++ killed by SIGSEGV (core dumped) +++
fish: 'strace pulseeffects' terminated by signal SIGSEGV (Address boundary error)

**Comment by M0Rf30** [comment] 2020-12-03 17:52
and pipewire-pulse:
```
: pulse-server 0x557fb3bbff80: [PulseEffects] ERROR command:21 (GET_SINK_INFO) tag:9 error:5 (No >
dic 03 18:50:01 arch-laptop pipewire-pulse[3795]: pulse-server 0x557fb3bbff80: [PulseEffects] ERROR command:36 (SET_SINK_VOLUME) tag:11 error:5 (>
dic 03 18:50:01 arch-laptop pipewire-pulse[3795]: 87: not ready

```

**Comment by wwmm** [comment] 2020-12-03 17:54
I am looking at the contents of the packages `pipewire-pulse` and `pipewire`. No Pulseaudio module is shipped with them. So as Pipewire is right now it is drop-in Pulseaudio replacement only for application that do not need to load Pulseaudio modules. Don't waste your time trying to debug PulseEffects on it. It won't work if we are not able to load Pulseaudio null sinks.

**Comment by Digitalone1** [comment] 2020-12-03 18:05
This means that also applications relying on gstreamer are not working? Like totem and epiphany...

**Comment by wwmm** [comment] 2020-12-03 18:09
>This means that also applications relying on gstreamer are not working?

At least `gst-launch-1.0` works. Other GStreamer applications are probably fine. And our GStreamer pipeline probably won't need to be changed. But everything else that is done in our `PulseManager` class will have to be rewritten for Pipewire. And we have to find out a way to redirect applications that to not rely on Pulseaudio null sinks. I still did not find out how Piepewire intends to handle this kind of operation.

**Comment by Digitalone1** [comment] 2020-12-03 18:16
Oh my God, that class is huge. I hope someone does a replacement package on AUR to keep the system update with the original pulseaudio because I can't stay without PulseEffects.

**Comment by wwmm** [comment] 2020-12-03 18:21
>Oh my God, that class is huge

Yes. It is huge. But many of those Pulseaudio functions are used by Pavucontrol too and as far as I could see Pavucontrol is working in Pipewire. So I expect that in some of those methods only a name change will be necessary in some functions. I say we will have to move to the Pipewire API because it does not seem we will be able to redirect applications in the same way that was done in Pulseaudio. That is what really concerns me now. If we are going to have the Pipewire way for that then we do this everywhere. Mixing Pulseaudio and Pipewire API will only make the code more confusing.

**Comment by wwmm** [comment] 2020-12-03 18:25
I suggest we continue this discussion in #397. I will close this issue.

**Closed by wwmm** 2020-12-03 18:25 UTC
