### ISSUE TITLE
Odd issue with 19.04 

### ISSUE THREAD

**Issue by CyberPhy** [wwmm/pulseeffects#490] opened 2019-04-20 13:53 UTC
Ive been having an issue after fresh install of Ubuntu 19.04 where PulseEffects would not play any audio until I turn off PulseEffects for the programs and then turn it back on.
It does this for every program (Steam Games,Chromium and Firefox) it seems to be a new bug with 19.04

**Comment by wwmm** [comment] 2019-04-20 13:59
Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects` so that we can see what is printed in the terminal. Maybe it gives some clues about what is happening. At least on Arch Linux there is no problem. So my guess is that you have a configuration problem.

**Comment by wwmm** [comment] 2019-04-20 14:00
Are you using flatpak or the native debian package?

**Comment by CyberPhy** [comment] 2019-04-20 21:34
Im using Native Debian

**Comment by CyberPhy** [comment] 2019-04-24 15:41
G_MESSAGES_DEBUG=pulseeffects pulseeffects
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.275: application: PE version: 4.5.9
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.276: pulse_manager: context is connecting
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.276: pulse_manager: context is authorizing
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.277: pulse_manager: context is setting name
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.277: pulse_manager: context is ready
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.277: pulse_manager: connected to: unix:/run/user/1000/pulse/native
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.277: pulse_manager: protocol version: 32
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.278: pulse_manager: Pulseaudio version: 12.2
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.278: pulse_manager: default pulseaudio source: alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-mono
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.278: pulse_manager: default pulseaudio sink: alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-stereo
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.278: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.278: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.278: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.280: pulse_manager: sink loaded
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.280: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.281: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.281: pulse_manager: default pulseaudio source audio format: s16le
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.282: pulse_manager: sink loaded
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.315: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.315: sie: using output device: alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-stereo
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.328: sie: limiter is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.332: sie: compressor is enabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.334: sie: filter is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.407: sie: equalizer is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.410: sie: reverb is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.412: sie: bass_enhancer is enabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.415: sie: exciter is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.418: sie: crossfeed is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.421: sie: maximizer is enabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.425: sie: multiband_compressor is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.427: sie: loudness is enabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.430: sie: gate is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.432: sie: pitch is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.438: sie: multiband_gate is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.441: sie: deesser is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.444: sie: stereo_tools is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.446: sie: convolver is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.449: sie: crystalizer is enabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.452: sie: autogain is enabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.456: sie: delay is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.474: soe: using output device: PulseEffects_mic
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.474: soe: using input device: alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-mono
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.475: soe: limiter is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.476: soe: compressor is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.477: soe: filter is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.491: soe: equalizer is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.492: soe: reverb is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.493: soe: gate is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.494: soe: deesser is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.495: soe: pitch is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.500: soe: webrtc is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.502: soe: multiband_compressor is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.504: soe: multiband_gate is already disabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.505: presets_manager: user presets directory already exists: /home/desktop/.config/PulseEffects
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.505: presets_manager: user presets directory already exists: /home/desktop/.config/PulseEffects/input
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.505: presets_manager: user presets directory already exists: /home/desktop/.config/PulseEffects/output
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:02.505: presets_manager: user presets directory already exists: /home/desktop/.config/PulseEffects/autoload
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:03.068: convolver_ui: irs directory already exists: /home/desktop/.config/PulseEffects/irs
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:03.733: sie: spectrum enabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:03.734: soe: spectrum enabled
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.269: sie: total latency: 0 ms
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.269: soe: total latency: 0 ms
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.395: sie: rtkit: changed GstPulseSrc:source thread real-time priority value to 4
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.397: pulse_settings_ui: added sink: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.398: pulse_settings_ui: added sink: alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-stereo
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.398: pulse_settings_ui: added source: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2.monitor
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.398: pulse_settings_ui: added source: alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-stereo.monitor
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.398: soe: using input device: alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-mono
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.398: pulse_settings_ui: input device changed: alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-mono
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.398: pulse_settings_ui: added source: alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-mono
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.402: sie: rtkit: changed GstQueue:queue0 thread real-time priority value to 4
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.406: sie: rtkit: changed GstPulseSrc:source thread real-time priority value to 4
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.406: sie: sampling rate: 44100 Hz
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.406: sie: NULL -> READY -> PLAYING
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.410: sie: READY -> PAUSED -> PLAYING
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.414: sie: pulsesrc latency [us]: 10000
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.414: sie: pulsesrc buffer [us]: 200000
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.414: sie: total latency: 0 ms
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.472: peadapter: pulseaudio block size 441 frames
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.472: peadapter: we will read in chunks of 512 frames
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.472: sie: pulsesink latency [us]: 10000
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.472: sie: pulsesink buffer [us]: 200000
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.472: sie: total latency: 0 ms
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.531: sie: total latency: 141 ms
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.533: sie: total latency: 141 ms
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.568: sie: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:04.568: sie: total latency: 141 ms
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:30.322: sie: PLAYING -> PAUSED -> READY
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:30.323: sie: PAUSED -> READY -> VOID_PENDING
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.065: sie: READY -> PAUSED -> PLAYING
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.068: sie: rtkit: changed GstPulseSrc:source thread real-time priority value to 4
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.072: sie: rtkit: changed GstQueue:queue0 thread real-time priority value to 4
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.076: sie: rtkit: changed GstPulseSrc:source thread real-time priority value to 4
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.076: sie: pulsesrc latency [us]: 10000
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.076: sie: pulsesrc buffer [us]: 200000
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.076: sie: total latency: 0 ms
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.076: sie: sampling rate: 44100 Hz
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.124: peadapter: pulseaudio block size 441 frames
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.124: peadapter: we will read in chunks of 512 frames
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.179: sie: total latency: 141 ms
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.179: sie: pulsesink latency [us]: 10000
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.179: sie: pulsesink buffer [us]: 200000
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.180: sie: total latency: 141 ms
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.180: sie: total latency: 141 ms
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.180: sie: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:31.181: sie: total latency: 141 ms
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:44.991: sie: PLAYING -> PAUSED -> READY
(pulseeffects:3956): pulseeffects-DEBUG: 11:40:44.993: sie: PAUSED -> READY -> VOID_PENDING

**Comment by wwmm** [comment] 2019-04-24 23:57
I see nothing unusual. In this log did you have to turn the app on and off?

**Comment by CyberPhy** [comment] 2019-04-25 14:28
Yeah

**Comment by wwmm** [comment] 2019-04-25 14:50
Really strange. As soon as PE was opened its pipeline was put in the playing state `PAUSED -> PLAYING -> VOID_PENDING`. I wonder if the flatpak package would show thee same issue in your system.

**Comment by CyberPhy** [comment] 2019-04-25 15:06
Video of the problem 
[https://drive.google.com/open?id=1IWc3ggmcvR0ipa1Z873fmH4fYJB9B9Tw](url)

**Comment by wwmm** [comment] 2019-04-26 15:16
Install Pavucontrol and take a print of the tabs `Playback`, `Recording` and `Output Devices` while it is still silent. I would like to see to which output device the browser is playing when there is no sound.

**Comment by wwmm** [comment] 2019-04-26 15:25
Taking a second look at the log there is something missing. Whe I enable/disable Chrome I have lines like:
```
pulse_manager: sink input: Chrome, idx = 71 removed from PE
pulse_manager: sink input: Chrome, idx = 71 moved to PE
```
It is strange they were not printed in your log when you used the switch.

**Comment by CyberPhy** [comment] 2019-04-26 16:58
that is odd would you like me to redo the log?

**Comment by wwmm** [comment] 2019-04-26 17:08
I think it is a good idea to redo it. This way we will know if these messages are never printed or if it was an isolated case.

**Comment by CyberPhy** [comment] 2019-05-03 16:46
Sorry for the late reply here are the logs
`G_MESSAGES_DEBUG=pulseeffects pulseeffects
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.317: application: PE version: 4.5.9
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.318: pulse_manager: context is connecting
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.318: pulse_manager: context is authorizing
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.319: pulse_manager: context is setting name
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.320: pulse_manager: context is ready
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.320: pulse_manager: connected to: unix:/run/user/1000/pulse/native
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.320: pulse_manager: protocol version: 32
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.320: pulse_manager: Pulseaudio version: 12.2
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.320: pulse_manager: default pulseaudio source: alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-mono
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.320: pulse_manager: default pulseaudio sink: alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-stereo
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.320: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.321: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.321: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.322: pulse_manager: sink loaded
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.322: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.324: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.324: pulse_manager: default pulseaudio source audio format: s16le
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.324: pulse_manager: sink loaded
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.365: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.366: sie: using output device: alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-stereo
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.384: sie: limiter is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.387: sie: compressor is enabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.390: sie: filter is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.457: sie: equalizer is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.460: sie: reverb is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.463: sie: bass_enhancer is enabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.465: sie: exciter is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.469: sie: crossfeed is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.471: sie: maximizer is enabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.476: sie: multiband_compressor is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.478: sie: loudness is enabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.481: sie: gate is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.483: sie: pitch is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.489: sie: multiband_gate is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.492: sie: deesser is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.495: sie: stereo_tools is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.497: sie: convolver is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.500: sie: crystalizer is enabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.502: sie: autogain is enabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.507: sie: delay is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.526: soe: using output device: PulseEffects_mic
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.526: soe: using input device: alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-mono
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.527: soe: limiter is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.529: soe: compressor is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.530: soe: filter is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.544: soe: equalizer is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.545: soe: reverb is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.546: soe: gate is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.547: soe: deesser is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.549: soe: pitch is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.553: soe: webrtc is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.555: soe: multiband_compressor is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.556: soe: multiband_gate is already disabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.558: presets_manager: user presets directory already exists: /home/desktop/.config/PulseEffects
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.558: presets_manager: user presets directory already exists: /home/desktop/.config/PulseEffects/input
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.558: presets_manager: user presets directory already exists: /home/desktop/.config/PulseEffects/output
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:46.558: presets_manager: user presets directory already exists: /home/desktop/.config/PulseEffects/autoload
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:47.119: convolver_ui: irs directory already exists: /home/desktop/.config/PulseEffects/irs
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:47.792: sie: spectrum enabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:47.793: soe: spectrum enabled
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.317: sie: total latency: 0 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.317: soe: total latency: 0 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.457: sie: rtkit: changed GstPulseSrc:source thread real-time priority value to 4
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.460: pulse_settings_ui: added sink: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.460: sie: rtkit: changed GstQueue:queue0 thread real-time priority value to 4
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.460: pulse_settings_ui: added sink: alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-stereo
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.460: pulse_settings_ui: added source: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2.monitor
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.461: pulse_settings_ui: added source: alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-stereo.monitor
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.461: soe: using input device: alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-mono
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.461: pulse_settings_ui: input device changed: alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-mono
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.461: pulse_settings_ui: added source: alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_E1_0000047292-00.analog-mono
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.466: sie: rtkit: changed GstPulseSrc:source thread real-time priority value to 4
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.466: sie: sampling rate: 44100 Hz
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.472: sie: NULL -> READY -> PLAYING
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.482: sie: READY -> PAUSED -> PLAYING
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.491: sie: pulsesrc latency [us]: 10000
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.491: sie: pulsesrc buffer [us]: 200000
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.491: sie: total latency: 0 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.522: peadapter: pulseaudio block size 441 frames
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.522: peadapter: we will read in chunks of 512 frames
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.522: sie: pulsesink latency [us]: 10000
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.522: sie: pulsesink buffer [us]: 200000
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.522: sie: total latency: 0 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.572: sie: total latency: 141 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.574: sie: total latency: 141 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.616: sie: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:48.616: sie: total latency: 141 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:52.415: sie: PLAYING -> PAUSED -> READY
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:52.416: sie: PAUSED -> READY -> VOID_PENDING
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:52.985: sie: READY -> PAUSED -> PLAYING
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:52.989: sie: rtkit: changed GstQueue:queue0 thread real-time priority value to 4
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:52.993: sie: rtkit: changed GstPulseSrc:source thread real-time priority value to 4
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.001: sie: rtkit: changed GstPulseSrc:source thread real-time priority value to 4
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.001: sie: sampling rate: 44100 Hz
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.002: sie: pulsesrc latency [us]: 10000
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.002: sie: pulsesrc buffer [us]: 200000
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.002: sie: total latency: 0 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.054: peadapter: pulseaudio block size 441 frames
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.054: peadapter: we will read in chunks of 512 frames
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.100: sie: total latency: 141 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.100: sie: pulsesink latency [us]: 10000
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.100: sie: pulsesink buffer [us]: 200000
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.101: sie: total latency: 141 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.101: sie: total latency: 141 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.101: sie: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:53.101: sie: total latency: 141 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:59.448: pulse_manager: sink input: Chromium, idx = 0 removed from PE
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:59.461: sie: PLAYING -> PAUSED -> READY
(pulseeffects:4984): pulseeffects-DEBUG: 12:44:59.463: sie: PAUSED -> READY -> VOID_PENDING
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.199: pulse_manager: sink input: Chromium, idx = 0 moved to PE
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.204: sie: READY -> PAUSED -> PLAYING
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.208: sie: rtkit: changed GstQueue:queue0 thread real-time priority value to 4
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.211: sie: rtkit: changed GstPulseSrc:source thread real-time priority value to 4
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.217: sie: rtkit: changed GstPulseSrc:source thread real-time priority value to 4
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.218: sie: sampling rate: 44100 Hz
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.219: sie: pulsesrc latency [us]: 10000
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.219: sie: pulsesrc buffer [us]: 200000
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.219: sie: total latency: 0 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.270: peadapter: pulseaudio block size 441 frames
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.270: peadapter: we will read in chunks of 512 frames
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.326: sie: total latency: 141 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.327: sie: pulsesink latency [us]: 10000
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.327: sie: pulsesink buffer [us]: 200000
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.328: sie: total latency: 141 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.328: sie: total latency: 141 ms
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.328: sie: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:4984): pulseeffects-DEBUG: 12:45:00.328: sie: total latency: 141 ms
`

**Comment by wwmm** [comment] 2019-05-04 00:51
Now the messages are there. I have to admit I have no idea about what is happening. There is no issue in the logs.

Considering that our pipeline is definitely playing and there is no sound the problem could be at a lower level. Maybe something in GStreamer installation is not ok. Or even in Pulseaudio. What is the output of the commands `pactl list sinks` and `pactl list sink-inputs` exactly before the moment you take action by changing the switch on/off? If Pulseaudio shows that the sound card is suspended or idle then GStreamer is lying and not actually playing anything.

**Comment by CyberPhy** [comment] 2019-05-08 04:04
well I reinstall 19.04 and its working great again 
I guess it was just a bad install of 19.04?

**Comment by wwmm** [comment] 2019-05-08 05:00
Maybe. No I wonder if trying on another user account would have made any difference. In any case I think we can close this issue. I hope this problem does not come back because I still have no idea of what could cause this XD

**Closed by wwmm** 2019-05-08 05:00 UTC

**Comment by GoogleBeEvil** [comment] 2019-05-08 14:27
actually . i have this issue some time ,i cant point out how to reproduce this issue,seems happened randomly

**Comment by wwmm** [comment] 2019-05-08 14:40
Are you also on ubuntu or in another distro?
