### ISSUE TITLE
Q: per channel configuration?

### ISSUE THREAD

**Issue by Hr46ph** [wwmm/pulseeffects#353] opened 2018-10-14 14:28 UTC
My right ear is half deaf in some frequencies. I've had hearing tests and have audiograms that I use to adjust frequencies per channel. On Windows I've been able to do this using Equalizer APO. My main use however is Linux and it would be great to be able to do the same. I basically lower both channels gain by 6 dB, lower the left channel by another 4 dB, then boost 4Khz by 10 dB on the right channel, 2 and 6 KHz get boosted by 4 dB.

Is this config possible with pulseeffects?

Thanks!

**Comment by wwmm** [comment] 2018-10-14 15:39
Unfortunately this is not possible at this moment. Equalizer APO was made with multi channel support in mind. As I never needed this I chose an approach focused on stereo. And to be honest it is not easy to apply effects to an arbitrary number of channels in GStreamer.

That being said it is not impossible to add support for what you want. There is no need for the whole pipeline to take a multi channel approach. It should be possible to do this only in the equalizer. I will think about this.

**Comment by Hr46ph** [comment] 2018-10-14 15:49
Thanks for the prompt reply!

What I really like about APO is to add channel modifiers before effects. Basically, the sound stream flows through a stack of (enabled) effects top-down, and before an effect you can add a channel modifier.

Currently, I just changed the balance minus 30% on the right channel and boosted 2/4/6 khz by about half of what I actually need on the right ear. It works reasonably well and I guess its a good compromise.

Really appreciate your willingness to consider this.

Thanks again!

**Comment by conceptualspace** [comment] 2018-10-19 17:21
another example use case would be the ability to set low/highpass filters on each channel for multispeaker setups (ie one pair of speakers get the low frequences and the other set of speakers get the high)

**Comment by wwmm** [comment] 2018-10-20 01:05
It is not easy to do that. Most of the plugins available in PulseEffects only work with 2 channels. So we have to be very careful and make sure that they are removed from the pipeline when a switch to more than 2 channels is made. There are other difficulties too. At this moment Pulseaudio's null sinks can not be reconfigured with a different number of channels on the fly.

**Comment by Damme** [comment] 2018-11-11 20:56
I would also really much want this feature with same reasons as Hr46ph.

**Comment by wwmm** [comment] 2018-12-30 01:47
I bring good news! I finally had the time to take a look at this. The code in our master branch is now capable of applying different equalization for the channels. People on Arch Linux can use the PKGBUILD in our source code to build a package. I still don't know when the next version will be released

**Comment by wwmm** [comment] 2018-12-30 20:19
Implemented in PulseEffects `4.4.2`

**Closed by wwmm** 2018-12-30 20:19 UTC
Labels: enhancement

**Comment by andreimarinescu** [comment] 2019-01-07 19:05
I hope I'm not mistaken by commenting on this thread, but since it's fairly recent I believe it might make sense. Any way to further split the channels on the equalizer for 5.1/7.1 setups? My use-case is that I'd like to increase the overall gain on channels 3 and 4 and I haven't found a way of doing this with pulseeffects so far.

**Comment by wwmm** [comment] 2019-01-07 19:50
No problems. At this moment this is not possible. And I don't know when we will be able to support this. This will require a somewhat elaborate code rewrite because we would have to create one instance of the Gstreamer equalizer for each channel. We also would need to change GStreamer's pipeline so it can handle multiple channels. GStreamer offers ways to do all that the problem is that at this moment Pulseaudio does not support some features we would need to handle multi channels. We need Pulseaudio's null sinks capable of being reconfigured on the fly. It seems there is some work done by Pulseaudio developers to support sampling rate reconfiguration in the null sinks. But I don't know if any work was done for the channels reconfiguration.

If all you want it to increase gain it does not have to be the equalizer. A volume plugin for the corresponding channels would be enough. But in any case we still have to wait for the Pulseaudio's null sink to be able to reconfigure its parameters on the fly. #288 is also waiting for this.

Something you could try is using pavucontrol to change the volume of only these channels. It has an option to split the channels volume if I am not mistaken

**Comment by andreimarinescu** [comment] 2019-01-12 20:04
Indeed, `pavucontrol` works perfectly for this, I was able to split the channels there and increase rear volume this way. And now it sounds amazing because I also have `pulseeffects`. Thanks!
