### ISSUE TITLE
About button in the Help window freezes the window without showing info

### ISSUE THREAD

**Issue by mzannoni** [wwmm/pulseeffects#320] opened 2018-08-28 07:44 UTC
I'm running PulseEffects on Fedora 28 through flathub repo (version 4.2.8).
In the new 'Help' window I've seen there's an 'About' botton at the end. This 'Help' window works correctly, until I click on 'About'.
When I do that, no 'about info' is shown anywhere and this 'Help' window freezes (all the content becomes unresponsive, but I can still close the window with the 'x' button).

**Comment by wwmm** [comment] 2018-08-28 14:41
I could not reproduce that here using the arch linux package
![screenshot from 2018-08-28 11-39-57](https://user-images.githubusercontent.com/16225172/44730371-2c134e80-aab7-11e8-9f01-c3b9b81e89f3.png)
@AsavarTzeth is the about info shown by the flatpak package in your computer? If yes then this could be a bug in the yelp version provided by fedora

**Comment by AsavarTzeth** [comment] 2018-08-28 14:56
I'll check in an hour or two, once I get home.

I would guess that yelp is provided by the gnome flatpak runtime, since the host might not have it installed.

**Comment by AsavarTzeth** [comment] 2018-08-28 16:00
I think I reproduced this with flatpak on Arch Linux. Here is the error:
```
(WebKitWebProcess:26): Gdk-ERROR **: 17:56:00.008: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 207 error_code 2 request_code 154 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

It would seem it agrees with you on it probably being a bug somewhere :)

**Comment by wwmm** [comment] 2018-08-28 16:11
Could it be that yelp needs some kind of access permission flatpak does not give? Here I only have a harmless warning when yelp is open:

`Recursion depth exceeded calculating bg color`

**Comment by AsavarTzeth** [comment] 2018-08-28 16:18
Yes I get that warning too (a lot of it), but I doubt its related.

I think this is actually much simpler. I compared the [Arch Linux PKGBUILD for webkit2gtk](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/webkit2gtk) and the manifest file for org.gnome.Platform//3.28 (found at /usr/manifest.json inside flatpak sandbox):
```
    {
      "name" : "WebKitGTK+",
      "buildsystem" : "cmake",
      "config-opts" : [
        "-DPORT=GTK",
        "-DCMAKE_BUILD_TYPE=Release",
        "-DCMAKE_INSTALL_PREFIX:PATH=/usr",
        "-DLIB_INSTALL_DIR:PATH=/usr/lib",
        "-DSYSCONF_INSTALL_DIR:PATH=/usr/etc",
        "-DSHARE_INSTALL_PREFIX:PATH=/usr/share",
        "-DINCLUDE_INSTALL_DIR:PATH=/usr/include",
        "-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON",
        "-DENABLE_MINIBROWSER=ON"
      ],
      "sources" : [
        {
          "url" : "https://webkitgtk.org/releases/webkitgtk-2.20.5.tar.xz",
          "sha256" : "15c0f8d26e9605afe0948d161ba5fd82efee8eda2debd409fd40a440ac3af990",
          "type" : "archive"
        }
      ],
      "build-options" : {
        "cflags" : "-g1",
        "cxxflags" : "-g1",
        "arch" : {
          "i386" : {
            "config-opts" : [
              "-DCMAKE_SYSTEM_PROCESSOR=i586"
            ]
          },
          "arm" : {
            "config-opts" : [
              "-DCMAKE_SYSTEM_PROCESSOR=arm",
              "-DENABLE_JIT=OFF"
            ]
          }
        }
      },
```

Notice that the flatpak runtime does not build with `-DENABLE_GTKDOC=ON`. I am currently doing a local build of webkit2gtk without that flag. So far I have confirmed that it is OFF by default).

Now to see if I can reproduce this issue on Arch with a local replacement package.

**Comment by AsavarTzeth** [comment] 2018-08-28 19:42
Nope, that was not it. Apparently it wasn't that simple, but too good to be true.

I still think its caused by some difference in the sdk/runtime, compared to Arch. The app and the runtime are mounted inside the same sandbox (namespace) so I highly doubt it could be related to permissions. However I could be wrong.

So, if I can't solve it I will simply report it upstream and hope for the best.

**Comment by wwmm** [comment] 2020-08-15 14:41
Is this still a problem?

**Comment by AsavarTzeth** [comment] 2020-09-02 13:43
Based upon the initial comment and a new attempt to reproduce this, no. I have no issues with the "About" section of "Help" window. It was a long time ago and seems likely to be one of those issues that resolved itself with updates to some dependencies.

**Comment by wwmm** [comment] 2020-09-02 14:17
Ok. I will close this issue.

**Closed by wwmm** 2020-09-02 14:17 UTC
