### ISSUE TITLE
Bluetooth speaker makes Pulse Effects crash

### ISSUE THREAD

**Issue by Lailah** [wwmm/pulseeffects#676] opened 2020-05-05 06:18 UTC
Description of problem:
Connecting Bluetooth speakers make Pulse Effects crash taking down the whole sound system with it.

Version-Release number of selected component (if applicable):
Pulse Effects 4.7.1 KDE Plasma 5.18  Fedora 32

How reproducible:
Turning the Bluetooth speakers on.

Steps to Reproduce:
1. Start Pulse Effects
2. Connect the Bluetooth speakers
3. Pulse Effects crashes and all sound disappears until you turn the speakers off and start Pulse Effects again.

Actual results:
Pulse crashes

Expected results:
Pulse keeps on

Additional info:
Bluetooth speakers model is Comiso M20. 
Pulse Effects works fine with headphones (plugged to the jack) and inbuilt speakers (ThinkPad T440s).
The error message points out to a missing loudness plugin.
No problems so far with headphones and the laptop's inbuilt speakers.

**Comment by Digitalone1** [comment] 2020-05-05 08:22
From terminal, `pulseeffects q`, then `G_MESSAGES_DEBUG=pulseeffects pulseeffects`

Report the output in a log as explained [here](https://github.com/wwmm/pulseeffects/wiki/Reporting-bugs).

Missing loudness plugin may suggest mda.lv2 package is not installed correctly. Do you see loudness plugin tab greyed out?

**Comment by Lailah** [comment] 2020-05-05 13:01
Hello.
The output is as following: 

(pulseeffects:2842): pulseeffects-DEBUG: 14:59:00.321: presets_manager: user presets directory already exists: /home/regenbogen/.config/PulseEffects
(pulseeffects:2842): pulseeffects-DEBUG: 14:59:00.321: presets_manager: user presets directory already exists: /home/regenbogen/.config/PulseEffects/input
(pulseeffects:2842): pulseeffects-DEBUG: 14:59:00.321: presets_manager: user presets directory already exists: /home/regenbogen/.config/PulseEffects/output
(pulseeffects:2842): pulseeffects-DEBUG: 14:59:00.321: presets_manager: user presets directory already exists: /home/regenbogen/.config/PulseEffects/autoload
(pulseeffects:2842): pulseeffects-DEBUG: 14:59:00.328: application:  destroyed
(pulseeffects:2842): pulseeffects-DEBUG: 14:59:00.328: presets_manager: destroyed

Yes, the loudness tab is present but greyed out.

**Comment by Lailah** [comment] 2020-05-05 13:02
Hello.
The output is as following:

(pulseeffects:2842): pulseeffects-DEBUG: 14:59:00.321: presets_manager: user presets directory already exists: /home/regenbogen/.config/PulseEffects
(pulseeffects:2842): pulseeffects-DEBUG: 14:59:00.321: presets_manager: user presets directory already exists: /home/regenbogen/.config/PulseEffects/input
(pulseeffects:2842): pulseeffects-DEBUG: 14:59:00.321: presets_manager: user presets directory already exists: /home/regenbogen/.config/PulseEffects/output
(pulseeffects:2842): pulseeffects-DEBUG: 14:59:00.321: presets_manager: user presets directory already exists: /home/regenbogen/.config/PulseEffects/autoload
(pulseeffects:2842): pulseeffects-DEBUG: 14:59:00.328: application: destroyed
(pulseeffects:2842): pulseeffects-DEBUG: 14:59:00.328: presets_manager: destroyed

Yes, the loudness tab is present but greyed out.

**Comment by wwmm** [comment] 2020-05-05 13:24
This log is too short. Probably because the command `pulseeffects q` should have been `pulseeffects -q` :-)

**Comment by Digitalone1** [comment] 2020-05-05 13:26
You're right @wwmm. Sorry.

Anyway,  @Lailah, to use loudness plugin you have to install mda-lv2 package, but it seems not provided by Fedora: 

> 2019-09-18 - Vasiliy N. Glazov <vascom2@gmail.com>  - 4.6.8-1
> - Update to 4.6.8
> - Drop lv2-mdala-plugins

https://fedora.pkgs.org/32/fedora-x86_64/pulseeffects-4.7.1-1.fc32.x86_64.rpm.html

So you have to install manually yourself: https://pkgs.org/search/?q=mda-lv2

If you want to use this plugin for volume balancing, you have also other options. The autogain, a compressor or the normalizer preset in my repository which don't rely on mda-lv2.

**Comment by wwmm** [comment] 2020-05-05 13:28
I doubt this crash is caused by a missing plugin. All of them should be optional. Something else is going on.

**Comment by Lailah** [comment] 2020-05-05 13:30
> I doubt this crash is caused by a missing plugin. All of them should be optional. Something else is going on.

Yes, the plugin is missing all the same with headphones and inbuilt speakers but in those cases, the programme doesn't crash.

**Comment by Lailah** [comment] 2020-05-05 13:38
> You're right @wwmm. Sorry.
> 
> Anyway, @Lailah, to use loudness plugin you have to install mda-lv2 package, but it seems not provided by Fedora:
> 
> > 2019-09-18 - Vasiliy N. Glazov [vascom2@gmail.com](mailto:vascom2@gmail.com)  - 4.6.8-1
> > 
> > * Update to 4.6.8
> > * Drop lv2-mdala-plugins
> 
> https://fedora.pkgs.org/32/fedora-x86_64/pulseeffects-4.7.1-1.fc32.x86_64.rpm.html
> 
> So you have to install manually yourself: https://pkgs.org/search/?q=mda-lv2
> 
> If you want to use this plugin for volume balancing, you have also other options. The autogain, a compressor or the normalizer preset in my repository which don't rely on mda-lv2.

I just want it not to crash. 
See the attachment to have a full text of the errors.

[Pulse Effects errors.txt](https://github.com/wwmm/pulseeffects/files/4581039/Pulse.Effects.errors.txt)

**Comment by Digitalone1** [comment] 2020-05-05 14:10
Are you sure lo the you posted is the part where the error occurred?

**Comment by Lailah** [comment] 2020-05-06 07:42
Here again, see attached file, please.
[More errors.txt](https://github.com/wwmm/pulseeffects/files/4585378/More.errors.txt)

**Comment by Digitalone1** [comment] 2020-05-06 07:50
> Here again, see attached file, please.
> [More errors.txt](https://github.com/wwmm/pulseeffects/files/4585378/More.errors.txt)

The application can't open the preset file. How did you save the "Speaker" preset? Can you try to make a new preset and delete the previous one?

**Comment by wwmm** [comment] 2020-05-06 12:37
@Lailah could you post this preset file here? At first I thought the crash happened because I was not checking if the preset file exists. But I am checking. So it seems there is something odd in the preset file.

But as far as "solving the problem goes" removing the `Speakers` preset file should fix the problem.

**Comment by wwmm** [comment] 2020-05-06 12:38
Could it be some kind of wrong permissions in the file?

**Comment by Vascom** [comment] 2020-05-06 18:54
If you think problem in lv2-mdala-plugins I can restore it.

**Comment by Lailah** [comment] 2020-05-06 21:45
> @Lailah could you post this preset file here? At first I thought the crash happened because I was not checking if the preset file exists. But I am checking. So it seems there is something odd in the preset file.
> 
> But as far as "solving the problem goes" removing the `Speakers` preset file should fix the problem.

Well, that's one issue.  I created that preset, but deleted it later on. Something went wrong though, and the preset wasn't there but a file with a long name was.  I moved this file to the bin and now Pulse Effects doesn't crash. 
I'm sending the file in case it's useful, it's a json.
[bluez_sink.FC_58_FA_C3_0A_B4.a2dp_sink:headset-output.zip](https://github.com/wwmm/pulseeffects/files/4589597/bluez_sink.FC_58_FA_C3_0A_B4.a2dp_sink.headset-output.zip)

**Comment by wwmm** [comment] 2020-05-06 22:31
I see nothing strange in this file. I have no idea of what happened

**Comment by Digitalone1** [comment] 2020-05-06 22:44
> I see nothing strange in this file. I have no idea of what happened

It's not a preset file. Was it generated by PE?

**Comment by wwmm** [comment] 2020-05-07 02:48
At some point @Lailah must have clicked on the preset autoload button. This action generated that file. I will take a look if there is something wrong in the preset autoload code

**Comment by wwmm** [comment] 2020-05-07 03:06
I did a few quick tests and if the preset is removed without disabling ts autoload profile first PE still tries to load the non existent preset. But at least on my computer the result was the disabling of all plugins. It did not crash. In any case it will be better to remove the autoload file if the preset it is not there anymore and do nothing after that instead of disabling the plugins. I will try to fix that this week.

**Comment by Digitalone1** [comment] 2020-05-07 05:36
Because you are using the git version, old version will crash on the json parsing.

**Comment by Lailah** [comment] 2020-05-07 09:04
> At some point @Lailah must have clicked on the preset autoload button. This action generated that file. I will take a look if there is something wrong in the preset autoload code

Probably yes, because I primarily use those speakers.

**Comment by wwmm** [comment] 2020-05-07 15:13
`Because you are using the git version, old version will crash on the json parsing.` I didn't even think about it hahaha :D

With the latest changes in the repository I think we can close this.

**Closed by wwmm** 2020-05-07 15:13 UTC

**Comment by Lailah** [comment] 2020-05-07 15:34
Thank you so much!
